# -*- coding: utf-8 -*-
"""修复 cyberDefense.ts 全部30天重复的 codeExamples/expertNotes/quizQ2-Q5"""
import re, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FPATH = os.path.join(BASE, 'src', 'data', 'cyberDefense.ts')

with open(FPATH, 'r', encoding='utf-8') as f:
    content = f.read()

# ===== 30天主题映射 =====
TOPICS = {
    'def-1': {'cn':'安全运营中心概述','en':'SOC Overview','kw':['SOC','安全运营','MSSP','SIEM','7x24']},
    'def-2': {'cn':'日志收集与管理','en':'Log Management','kw':['日志','Windows Event','Syslog','rsyslog','Filebeat']},
    'def-3': {'cn':'SIEM系统部署','en':'SIEM Deployment','kw':['ELK','Elasticsearch','Kibana','Logstash','告警规则']},
    'def-4': {'cn':'入侵检测与防御','en':'IDS/IPS','kw':['Snort','Suricata','IDS','IPS','规则检测']},
    'def-5': {'cn':'异常行为分析','en':'Anomaly Detection','kw':['UEBA','Isolation Forest','行为基线','异常检测','机器学习']},
    'def-6': {'cn':'事件分类与分级','en':'Incident Classification','kw':['事件分类','定级','紧急','高危','事件报告']},
    'def-7': {'cn':'应急响应PDCERF','en':'Incident Response','kw':['PDCERF','准备','检测','遏制','根除','恢复']},
    'def-8': {'cn':'防火墙技术','en':'Firewall','kw':['iptables','nftables','状态跟踪','ESTABLISHED','NAT']},
    'def-9': {'cn':'WAF部署与配置','en':'WAF Deployment','kw':['WAF','ModSecurity','OWASP CRS','Web防护','误报']},
    'def-10': {'cn':'VPN与网络隔离','en':'VPN & Segmentation','kw':['VPN','OpenVPN','WireGuard','DMZ','零信任','VLAN']},
    'def-11': {'cn':'IDS/IPS调优','en':'IDS/IPS Tuning','kw':['误报','False Positive','规则调优','告警过滤','性能']},
    'def-12': {'cn':'DDoS防护','en':'DDoS Protection','kw':['DDoS','SYN Flood','清洗中心','CDN','syncookies','anycast']},
    'def-13': {'cn':'DNS安全','en':'DNS Security','kw':['DNS','DNSSEC','DoH','DNS劫持','DNS隧道','BIND']},
    'def-14': {'cn':'CDN与抗攻击','en':'CDN & Anti-DDoS','kw':['CDN','Anycast','高可用','源站隐藏','负载均衡']},
    'def-15': {'cn':'Linux安全加固','en':'Linux Hardening','kw':['SSH','文件权限','CIS','密码策略','Lynis','审计']},
    'def-16': {'cn':'Windows AD安全','en':'AD Security','kw':['AD','域控','BloodHound','LAPS','SMBv1','组策略']},
    'def-17': {'cn':'数据库安全','en':'Database Security','kw':['MySQL','SQL注入','参数化查询','审计','加密备份','最小权限']},
    'def-18': {'cn':'Docker容器安全','en':'Docker Security','kw':['Docker','容器','非root','Trivy','Falco','镜像扫描']},
    'def-19': {'cn':'云安全基础','en':'Cloud Security','kw':['AWS','S3','IAM','CWPP','CSPM','责任共担']},
    'def-20': {'cn':'API安全防护','en':'API Security','kw':['API','OAuth','JWT','限流','Kong','网关','OWASP API']},
    'def-21': {'cn':'安全开发生命周期','en':'SDL','kw':['SDL','STRIDE','SAST','DAST','OWASP Top10','威胁建模']},
    'def-22': {'cn':'等级保护2.0概述','en':'等保2.0','kw':['等保','GB/T 22239','定级','保护对象','测评']},
    'def-23': {'cn':'等级保护建设流程','en':'等保建设','kw':['备案','差距分析','整改','定级','公安机关','测评机构']},
    'def-24': {'cn':'风险评估方法','en':'Risk Assessment','kw':['FRAP','风险矩阵','资产','威胁','脆弱性','风险处置']},
    'def-25': {'cn':'灾难恢复与业务连续性','en':'DR & BCP','kw':['RPO','RTO','冷备','热备','3-2-1','演练']},
    'def-26': {'cn':'安全策略与制度','en':'Security Policies','kw':['策略','制度','流程','基线','ISO 27001','合规']},
    'def-27': {'cn':'安全意识培训','en':'Security Awareness','kw':['钓鱼邮件','Gophish','社工','培训','演练','安全意识']},
    'def-28': {'cn':'红蓝对抗','en':'Red vs Blue','kw':['红队','蓝队','ATT&CK','CTF','攻击模拟','溯源']},
    'def-29': {'cn':'威胁情报收集','en':'Threat Intelligence','kw':['IOC','VirusTotal','MISP','威胁情报','TTP','OTX']},
    'def-30': {'cn':'安全运营体系建设','en':'SOC Building','kw':['SOC','SIEM','SOAR','成熟度','KPI','运营指标']},
}

# ===== 生成代码示例 =====
def gen_code(day_id):
    t = TOPICS[day_id]
    codes = {
        'def-1': ('bash','# SOC值班检查清单\necho "=== 每日安全巡检 ====\ndate\nwho /var/log/wtmp|tail -5  # 最近登录\nnetstat -tulnp|grep LISTEN  # 开放端口\ndf -h /var/log                # 日志磁盘\necho "告警数:" $(grep -c ALERT /var/log/siem/alerts.log)','SOC日常巡检脚本：检查登录、端口、磁盘和告警数量'),
        'def-2': ('bash','# Filebeat收集系统日志\n# /etc/filebeat/filebeat.yml\nfilebeat.inputs:\n- type: log\n  paths:\n    - /var/log/syslog\n    - /var/log/auth.log\noutput.elasticsearch:\n  hosts: ["localhost:9200"]\n# 启动: systemctl start filebeat','Filebeat日志采集配置，将syslog和auth.log发送到Elasticsearch'),
        'def-3': ('yaml','# ELK Docker部署\ndocker run -d --name es \\\n  -e "discovery.type=single-node" \\\n  -p 9200:9200 elasticsearch:8.10.0\ndocker run -d --name kibana \\\n  --link es:elasticsearch \\\n  -p 5601:5601 kibana:8.10.0\n# 访问 http://localhost:5601','ELK快速部署：Docker启动Elasticsearch+Kibana'),
        'def-4': ('bash','# Snort检测规则示例\nalert tcp any any -> $HOME_NET 22 \\\n  (msg:"SSH暴力破解"; \\\n   content:"Failed password"; \\\n   threshold:type threshold,track by_src,count 5,seconds 60; sid:1000001;)\nalert icmp any any -> $HOME_NET any \\\n  (msg:"大ICMP包(隧道)"; dsize:>800; sid:1000002;)\n# 运行: snort -c /etc/snort/snort.conf -i eth0 -A console','Snort规则：检测SSH暴力破解和ICMP隧道攻击'),
        'def-5': ('python','from sklearn.ensemble import IsolationForest\nimport numpy as np\n# 模拟登录数据: [hour, attempts, src_ips]\ndata = [[9,1,1],[10,2,1],[3,50,10],[9,3,1],[2,30,5]]\nmodel = IsolationForest(contamination=0.2)\npred = model.fit_predict(data)\nfor i,p in enumerate(pred):\n    if p==-1: print(f"异常! 记录{i}: {data[i]}")\n# 凌晨大量失败登录=异常','Isolation Forest异常登录检测，识别非正常时段的大量登录尝试'),
        'def-6': ('python','# 安全事件自动分级\nLEVELS={"紧急":{"响应":"15分钟","例":"勒索软件"},"高危":{"响应":"1h","例":"数据泄露"},"中危":{"响应":"4h","例":"账号被盗"},"低危":{"响应":"24h","例":"端口扫描"}}\ndef classify(event):\n    if "ransomware" in event.lower(): return "紧急"\n    if "数据泄露" in event: return "高危"\n    if "暴力破解" in event: return "中危"\n    return "低危"\n# 测试\nevents=["检测到勒索软件","数据库异常导出","SSH暴力破解"]\nfor e in events: print(f"[{classify(e)}] {e}")','安全事件自动分类分级，根据关键字匹配响应等级'),
        'def-7': ('bash','# PDCERF应急响应命令速查\n# P-Prepare: 确认工具就绪\nls /opt/ir_tools/;cat /etc/ir_contacts.txt\n# D-Detect: 确认事件\nwho /var/log/wtmp|tail;netstat -tulnp;ps aux --sort=-%mem|head -5\n# C-Contain: 隔离\niptables -A INPUT -s 恶意IP -j DROP\n# E-Eradicate: 清除\nfind / -name "*.malware" -delete\n# R-Recover: 恢复\nsystemctl restart nginx\necho "恢复完成 $(date)"','PDCERF实战命令速查表：从检测到恢复的完整命令序列'),
        'def-8': ('bash','# iptables安全基线配置\niptables -F && iptables -X\niptables -P INPUT DROP\niptables -P FORWARD DROP\niptables -P OUTPUT ACCEPT\niptables -A INPUT -i lo -j ACCEPT\niptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT\niptables -A INPUT -p tcp --dport 22 -j ACCEPT\niptables -A INPUT -p tcp --dport 80 -j ACCEPT\niptables -A INPUT -p tcp --dport 443 -j ACCEPT\n# SYN Flood防护\niptables -A INPUT -p tcp --syn -m limit --limit 10/s -j ACCEPT\niptables -A INPUT -p tcp --syn -j DROP\niptables-save > /etc/iptables/rules.v4','iptables防火墙安全基线：默认拒绝+按需开放+SYN Flood防护'),
        'def-9': ('bash','# ModSecurity WAF配置\nSecRuleEngine On\nSecRequestBodyLimit 13107200\n# SQL注入检测\nSecRule ARGS "@rx (?:select|union|insert|drop).*?(?:from|into)" \\\n  "id:100001,phase:2,deny,status:403,msg:\'SQL Injection\'"\n# XSS检测\nSecRule ARGS "@rx <script.*?>" \\\n  "id:100002,phase:2,deny,status:403,msg:\'XSS Attack\'"\n# 启用OWASP CRS\nInclude /etc/modsecurity/owasp-crs/crs-setup.conf\nInclude /etc/modsecurity/owasp-crs/rules/*.conf','ModSecurity自定义规则：检测SQL注入和XSS攻击并返回403'),
        'def-10': ('bash','# OpenVPN服务器搭建速查\napt-get install openvpn easy-rsa\nmake-cadir ~/openvpn-ca && cd ~/openvpn-ca\n./easyrsa init-pki\n./easyrsa build-ca nopass\n./easyrsa gen-req server nopass\n./easyrsa sign-req server server\n./easyrsa gen-dh\n# 配置 /etc/openvpn/server.conf:\n# port 1194; proto udp; dev tun;\n# server 10.8.0.0 255.255.255.0;\n# cipher AES-256-GCM;\n# push "redirect-gateway def1"\nsystemctl start openvpn@server\nip addr show tun0  # 验证隧道','OpenVPN服务器部署流程：PKI初始化→证书签发→服务启动'),
        'def-11': ('python','# IDS告警过滤与误报分析\nalerts=["ICMP 192.168.1.1->10.0.0.1","SYN Flood 10.0.0.5","ICMP 192.168.1.1->10.0.0.1","SSH Brute 172.16.0.99","ICMP 192.168.1.1->10.0.0.1"]\nwhitelist=["192.168.1.1"]  # 可信IP\nfp=[a for a in alerts if a.split()[1] in whitelist]\nvalid=[a for a in alerts if a.split()[1] not in whitelist]\nprint(f"总告警:{len(alerts)} 误报(已过滤):{len(fp)} 有效:{len(valid)}")\nprint(f"误报率:{len(fp)/len(alerts)*100:.0f}%")','IDS告警过滤脚本：通过IP白名单过滤误报并计算有效告警率'),
        'def-12': ('bash','# Linux SYN Cookie DDoS防护\necho 1 > /proc/sys/net/ipv4/tcp_syncookies\necho 2048 > /proc/sys/net/ipv4/tcp_max_syn_backlog\necho 2 > /proc/sys/net/ipv4/tcp_synack_retries\necho 180000 > /proc/sys/net/ipv4/tcp_max_tw_buckets\necho "1024 65000" > /proc/sys/net/ipv4/ip_local_port_range\n# 持久化到 /etc/sysctl.conf\nsysctl -p\n# 查看SYN队列状态\nss -s | grep syn','SYN Cookie+DDoS内核参数调优：启用SYN Cookie并优化半连接队列'),
        'def-13': ('bash','# DNSSEC配置与验证\ncd /etc/bind\n# 生成ZSK和KSK密钥\ndnssec-keygen -a RSASHA256 -b 2048 -n ZONE example.com\ndnssec-keygen -f KSK -a RSASHA256 -b 4096 -n ZONE example.com\n# 签名区域\ndnssec-signzone -A -o example.com -t example.com.db\n# named.conf启用DNSSEC\necho \'dnssec-validation auto;\' >> named.conf.options\nsystemctl restart bind9\n# 验证: dig +dnssec example.com A (应有ad标志)\ndig +dnssec example.com A','DNSSEC配置：生成密钥→签名区域→验证响应真实性'),
        'def-14': ('bash','# CDN安全配置 - Cloudflare API\n# 1.强制HTTPS\ncurl -X PATCH "https://api.cloudflare.com/.../{zone}/settings/always_use_https" -d \'{"value":"on"}\'\n# 2.WAF规则: 阻止SQL注入\ncurl -X POST "https://api.cloudflare.com/.../{zone}/firewall/rules" -d \'{"expression":"(http.request.uri.query contains \\"union select\\")","action":"block"}\'\n# 3.验证源站隐藏\ncurl -I https://example.com | grep "cf-ray"  # 应包含CDN标识\nnslookup example.com  # 应返回CDN IP而非源站IP','CDN安全配置脚本：强制HTTPS+WAF规则+源站隐藏验证'),
        'def-15': ('bash','# Linux安全加固一键脚本\n#!/bin/bash\n# 1.SSH加固\nsed -i "s/^#PermitRootLogin.*/PermitRootLogin no/" /etc/ssh/sshd_config\nsed -i "s/^#PasswordAuthentication.*/PasswordAuthentication no/" /etc/ssh/sshd_config\necho "MaxAuthTries 3" >> /etc/ssh/sshd_config\nsystemctl restart sshd\n# 2.密码策略\nsed -i "s/^PASS_MAX_DAYS.*/PASS_MAX_DAYS 90/" /etc/login.defs\n# 3.锁定无用账户\nfor u in games ftp news lp; do usermod -L $u 2>/dev/null; done\n# 4.关键文件权限\nchmod 600 /etc/shadow; chmod 700 /root\n# 5.审计\napt-get install -y lynis && lynis audit system --quick\necho "加固完成！请查看Lynis评分"','Linux一键加固脚本：SSH强化+密码策略+账户管理+安全审计'),
        'def-16': ('powershell','# Windows AD安全审计\nauditpol /set /category:"Logon/Logoff" /success:enable /failure:enable\nauditpol /set /category:"Account Management" /success:enable /failure:enable\n# 禁用SMBv1\nSet-SmbServerConfiguration -EnableSMB1Protocol $false -Force\n# 检查Protected Users组\nGet-ADGroupMember "Protected Users" | Select Name\n# 查找未过期密码的用户(高风险)\nGet-ADUser -Filter {PasswordNeverExpires -eq $true -and Enabled -eq $true}\n# 检查域管理员成员\nGet-ADGroupMember "Domain Admins" | Select Name,SamAccountName','AD安全审计PowerShell：启用审核+禁用SMBv1+检查高风险配置'),
        'def-17': ('sql','-- MySQL安全加固SQL\n-- 1.删除匿名用户和测试库\nDELETE FROM mysql.user WHERE User="";\nDROP DATABASE IF EXISTS test;\n-- 2.创建最小权限账户\nCREATE USER app_user@"10.0.0.%" IDENTIFIED BY "Str0ngP@ss!";\nGRANT SELECT,INSERT,UPDATE ON app_db.* TO app_user@"10.0.0.%";\n-- 3.连接限制\nSET GLOBAL max_connections=300;\nSET GLOBAL max_connect_errors=10;\n-- 4.启用审计\nINSTALL PLUGIN audit_log SONAME "audit_log.so";\nSET GLOBAL audit_log_policy=ALL;\n-- 5.参数化查询(防注入)\nPREPARE stmt FROM "SELECT * FROM users WHERE name=?";\nSET @name="admin"; EXECUTE stmt USING @name;\n-- 6.检查安全设置\nSHOW VARIABLES LIKE "%ssl%";\nSELECT user,host,plugin FROM mysql.user;','MySQL安全加固：账户管理+审计启用+参数化查询防注入'),
        'def-18': ('dockerfile','# Docker安全最佳实践Dockerfile\nFROM alpine:3.19\nRUN addgroup -S app && adduser -S appuser -G app\nWORKDIR /app\nCOPY --chown=appuser:app . /app\nUSER appuser  # 非root运行\nHEALTHCHECK --interval=30s --timeout=3s \\\n  CMD wget -q http://localhost:8080/health || exit 1\nEXPOSE 8080\nCMD ["python3","app.py"]\n# 扫描: trivy image myapp\n# 运行: docker run --read-only --user 1000:1000 myapp','Docker安全Dockerfile：非root用户+健康检查+最小基础镜像'),
        'def-19': ('hcl','# AWS IAM最小权限策略 (Terraform)\nresource "aws_iam_policy" "readonly" {\n  name = "ReadOnlyPolicy"\n  policy = jsonencode({\n    Version = "2012-10-17"\n    Statement = [{\n      Effect = "Allow"\n      Action = ["s3:GetObject","ec2:Describe*","rds:Describe*"]\n      Resource = "*"\n      Condition = {Bool = {"aws:SecureTransport":"true"}}\n    }]\n  })\n}\n# S3桶防泄露配置\nresource "aws_s3_bucket_public_access_block" "block" {\n  bucket = aws_s3_bucket.secure.id\n  block_public_acls = true\n  block_public_policy = true\n  restrict_public_buckets = true\n}\n# 审计: prowler aws','AWS Terraform安全配置：IAM最小权限+S3防公开泄露'),
        'def-20': ('javascript','// API安全中间件 (Express.js)\nconst rateLimit=require("express-rate-limit");\nconst helmet=require("helmet");\nconst jwt=require("jsonwebtoken");\napp.use(rateLimit({windowMs:15*60000,max:100}));\napp.use(helmet());\n// JWT认证\nfunction auth(req,res,next){\n  const token=req.headers.authorization?.split(" ")[1];\n  if(!token) return res.status(401).json({error:"No token"});\n  try{req.user=jwt.verify(token,process.env.SECRET);next();}\n  catch{return res.status(403).json({error:"Invalid token"});}\n}\n// 输入验证\nconst {body,validationResult}=require("express-validator");\napp.post("/api/users",[\n  body("email").isEmail().normalizeEmail(),\n  body("name").trim().isLength({min:2})\n],(req,res)=>{\n  const err=validationResult(req);\n  if(!err.isEmpty()) return res.status(400).json({errors:err.array()});\n  /* ... */\n});','Express API安全：限流+Helmet头+JWT认证+输入验证'),
        'def-21': ('python','# SAST代码安全扫描速查\nimport subprocess,json\nprint("[1] npm依赖审计...")\nr=subprocess.run(["npm","audit","--json"],capture_output=True,text=True)\nd=json.loads(r.stdout)\nhigh=sum(1 for v in d.get("vulnerabilities",{}).values() if v.get("severity")in["high","critical"])\nprint(f"高危/严重漏洞: {high}个")\nprint("[2] 代码模式检查...")\npatterns={"硬编码密钥":"(password|secret|api_key)\\\\s*=\\\\s*[\\"\\\']","SQL注入风险":"f\\".*SELECT.*\\{","危险eval":"eval\\\\(\\\\)"}\nfor name,pat in patterns.items():\n    r=subprocess.run(["grep","-rc",pat,"./src/"],capture_output=True,text=True)\n    if r.stdout.strip(): print(f"  ⚠ {name}: {r.stdout.strip()}")','SDL代码扫描脚本：依赖审计+危险模式检查(硬编码/注入/eval)'),
        'def-22': ('bash','# 等保2.0合规自检脚本\ncheck_auth(){ echo "=== 身份鉴别 ===";grep -E "^PASS_MAX_DAYS|^PASS_MIN_DAYS" /etc/login.defs;grep pam_cracklib /etc/pam.d/common-password||echo "WARN:密码复杂度未启用";grep pam_tally2 /etc/pam.d/common-auth||echo "WARN:登录锁定未启用";}\ncheck_access(){ echo "=== 访问控制 ===";grep -E "^PermitRootLogin|^PasswordAuthentication" /etc/ssh/sshd_config;find / -perm -4000 -type f 2>/dev/null|head -5|while read f;do echo "SUID: $f";done;}\ncheck_audit(){ echo "=== 安全审计 ===";systemctl is-active auditd rsyslog;ls -la /var/log/auth.log /var/log/secure 2>/dev/null;}\ncheck_auth;check_access;check_audit\necho "=== 检查完成 ==="','等保2.0自检脚本：覆盖身份鉴别+访问控制+安全审计三大类'),
        'def-23': ('python','# 等保定级辅助评估\nclass GradingTool:\n    def assess(self,answers):\n        score=0\n        for q,w in [("系统中断影响核心业务?",5),("数据泄露造成重大损失?",4),("涉及大量个人信息?",4),("属关键基础设施?",5)]:\n            if answers.get(q): score+=w\n        return score\n    def level(self,score):\n        if score>=15: return "第四/五级-强制/专控保护"\n        if score>=10: return "第三级-监督保护"\n        if score>=5: return "第二级-指导保护"\n        return "第一级-自主保护"\n# 示例\ngt=GradingTool()\nanswers={"系统中断影响核心业务?":True,"数据泄露造成重大损失?":True,"涉及大量个人信息?":True,"属关键基础设施?":False}\ns=gt.assess(answers)\nprint(f"评分:{s}/18 建议:{gt.level(s)}")','等保定级评估工具：基于业务影响评分自动建议保护等级'),
        'def-24': ('python','# FRAP风险评估计算器\nclass RiskCalc:\n    def calc(self,asset_val,threat_likelihood,vuln_severity):\n        return asset_val*threat_likelihood*vuln_severity\n    def classify(self,score):\n        if score>=50: return "极高"\n        if score>=25: return "高"\n        if score>=10: return "中"\n        return "低"\n    def treat(self,level):\n        return {"极高":"规避/立即处置","高":"缓解/制定计划","中":"缓解/加强措施","低":"接受/保持监控"}[level]\nrc=RiskCalc()\nassets=[("核心DB",5,3,4),("Web Server",4,4,3),("备份",3,1,2)]\nfor name,v,t,f in assets:\n    r=rc.calc(v,t,f)\n    l=rc.classify(r)\n    print(f"{name}: 风险值={r} {l}风险 → {rc.treat(l)}")','FRAP风险评估工具：风险=资产×威胁×脆弱性，自动计算并给出处置建议'),
        'def-25': ('bash','# 灾难恢复演练脚本\nBACKUP_DIR="/backup/$(date +%Y%m%d)"\nmkdir -p $BACKUP_DIR\n# 1.全量备份+加密\nmysqldump --all-databases --single-transaction | gzip > $BACKUP_DIR/full.sql.gz\nopenssl enc -aes-256-cbc -in $BACKUP_DIR/full.sql.gz -out $BACKUP_DIR/full.sql.gz.enc -pass pass:$(cat /etc/backup.key)\n# 2.异地同步\nrsync -avz /backup/ backup@remote:/backup/ -e "ssh -i /root/.ssh/backup_key"\n# 3.恢复演练(S TART=$SECONDS)\ngunzip < $BACKUP_DIR/full.sql.gz | mysql\necho "RTO=$(( (SECONDS-START)/60 ))分钟"\necho "数据行数: $(mysql -e \'SELECT COUNT(*) FROM app.users\')"','灾难恢复脚本：加密备份→异地同步→恢复演练→RTO验证'),
        'def-26': ('python','# 安全策略合规检查\nPOLICIES={"密码":{"min_len":12,"max_age":90,"special":True},"访问":{"mfa":True,"lockout":5},"数据":{"encrypt_rest":True,"retention_days":365}}\ndef check(config):\n    v=[]\n    if config.get("pwd_min_len",0)<POLICIES["密码"]["min_len"]: v.append("密码长度不达标")\n    if POLICIES["访问"]["mfa"] and not config.get("mfa"): v.append("MFA未启用")\n    if POLICIES["数据"]["encrypt_rest"] and not config.get("encrypt"): v.append("静态加密未启用")\n    return v\ncfg={"pwd_min_len":8,"mfa":False,"encrypt":True}\nissues=check(cfg)\nif issues:\n    for i in issues: print(f"❌ {i}")\nelse: print("✅ 全部合规")','安全策略合规检查引擎：自动验证密码/MFA/加密是否符合策略要求'),
        'def-27': ('python','# 钓鱼邮件智能检测\ndef analyze(content,sender,links):\n    score=0;alerts=[]\n    urgent=["立即","紧急","马上","锁定","urgent","suspended"]\n    for kw in urgent:\n        if kw in content.lower():score+=10;alerts.append(f"紧迫词:{kw}");break\n    domain=sender.split("@")[1] if "@" in sender else ""\n    if domain not in ["company.com","bank.com"]:score+=15;alerts.append(f"可疑发件域:{domain}")\n    for text,url in links:\n        import re;from urllib.parse import urlparse\n        if re.match(r"\\d+\\.\\d+\\.\\d+\\.\\d+",urlparse(url).netloc):score+=15;alerts.append("链接使用IP地址")\n    if score>=40:return "🔴 高风险-钓鱼邮件"\n    if score>=20:return "🟡 中风险-需确认"\n    return "🟢 低风险"\n# 测试\nr=analyze("您的帐户将被锁定!请立即点击验证!","admin@fake-login.com",[("https://bank.com","http://192.168.1.1/phish")])\nprint(f"判定: {r}")','钓鱼邮件检测器：紧迫感词+发件域+IP链接多维度分析'),
        'def-28': ('python','# ATT&CK原子测试与检测验证\ndef atomic_test(name,tid,cmd):\n    import subprocess,time\n    print(f"[{tid}] {name}")\n    start=time.time()\n    r=subprocess.run(cmd,shell=True,capture_output=True,text=True,timeout=30)\n    dur=time.time()-start\n    status="✅ 执行成功" if r.returncode==0 else "❌ 失败"\n    print(f"{status} ({dur:.1f}s)")\n    return {"technique":tid,"success":r.returncode==0}\ntests=[\n    ("PowerShell下载","T1059.001","powershell -c \\"iwr http://test/test -OutFile t.txt\\""),\n    ("系统信息收集","T1082","systeminfo"),\n    ("注册表持久化","T1547.001","reg add HKLM\\\\Software\\\\...\\\\Run /v test /t REG_SZ /d cmd.exe"),\n]\nresults=[atomic_test(n,t,c) for n,t,c in tests]\nprint(f"\\n测试数:{len(results)} 成功:{sum(1 for r in results if r[\'success\'])}")','ATT&CK原子测试框架：自动化执行攻击模拟并记录结果'),
        'def-29': ('python','# 威胁情报IOC查询\ndef check_hash_vt(file_hash,api_key):\n    import requests\n    url=f"https://www.virustotal.com/api/v3/files/{file_hash}"\n    r=requests.get(url,headers={"x-apikey":api_key},timeout=10)\n    if r.status_code==200:\n        d=r.json()\n        m=d["data"]["attributes"]["last_analysis_stats"]["malicious"]\n        return {"hash":file_hash[:12],"malicious":m,"risk":"HIGH" if m>0 else "LOW"}\n    return {"hash":file_hash[:12],"error":"query failed"}\ndef check_ip_otx(ip):\n    import requests\n    r=requests.get(f"https://otx.alienvault.com/api/v1/indicators/IPv4/{ip}/general",timeout=10)\n    if r.status_code==200:\n        p=len(r.json()["pulse_info"]["pulses"])\n        return {"ip":ip,"pulses":p,"risk":"HIGH" if p>5 else "MEDIUM" if p>0 else "LOW"}\n    return {"ip":ip,"risk":"UNKNOWN"}\nprint(check_ip_otx("8.8.8.8"))  # 示例查询','威胁情报查询工具：VirusTotal文件哈希+AlienVault OTX IP信誉'),
        'def-30': ('python','# SOC运营KPI仪表盘\nclass SOCDashboard:\n    def __init__(self):self.alerts_total=0;self.mttd=[];self.by_sev={"紧急":0,"高危":0,"中危":0,"低危":0}\n    def record(self,severity,detect_min):self.alerts_total+=1;self.by_sev[severity]=self.by_sev.get(severity,0)+1;self.mttd.append(detect_min)\n    def report(self):\n        avg_mttd=sum(self.mttd)/len(self.mttd) if self.mttd else 0\n        return f"总告警:{self.alerts_total}\\nMTTD:{avg_mttd:.1f}min\\n分布:{self.by_sev}"\nsoc=SOCDashboard()\nsoc.record("紧急",12);soc.record("高危",45);soc.record("中危",120);soc.record("中危",90)\nprint(soc.report())','SOC运营仪表盘：MTTD统计+事件分级分布+告警总量汇总'),
    }
    return codes[day_id]

# ===== 生成大神笔记 =====
def gen_notes(day_id):
    t = TOPICS[day_id]
    notes = {
        'def-1': [{"author":"赵刚","title":"SOC不是工具堆砌","content":"SOC的核心是人+流程+工具的有机结合。先建团队和流程，再选工具。最大的坑是买了SIEM没人会用，变成昂贵的日志存储器。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"孙婷","title":"安全分析师成长路径","content":"L1→L2→L3的晋升关键是：L1掌握工具和流程，L2理解攻击手法，L3能威胁狩猎和逆向。建议每半年做技能评估。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"周明","title":"SOC工具链选型建议","content":"ELK适合快速起步，Splunk适合预算充足的大企业，Wazuh是开源HIDS的好选择。关键是工具间要形成闭环。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-2': [{"author":"赵刚","title":"日志标准化是基础","content":"日志格式不统一是分析的最大障碍。强制所有系统输出JSON格式并遵循ECS规范，跨系统关联才能落地。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"刘磊","title":"大规模日志采集经验","content":"采集500台服务器日志的经验：必须配置反压机制，用Pipeline预处理分担Logstash压力，监控采集延迟。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"陈琳","title":"Windows日志分析要点","content":"EventID 4624/4625是登录审计核心，4688是进程创建，5145是网络共享访问。建议启用Sysmon增强日志粒度。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-3': [{"author":"赵刚","title":"SIEM项目成败关键","content":"SIEM成败取决于运营能力而非产品品牌。选了Splunk没有懂规则的人也是摆设。建议先拿ELK练手培养团队。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"周明","title":"告警规则编写艺术","content":"好规则是信噪比的平衡。用统计模型代替固定阈值，聚合同类告警减少重复。规则要随业务变化持续调优。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"黄敏","title":"ELK性能优化实战","content":"ES分片≤50GB、Logstash worker优化、Kibana查询缓存，三项优化后查询速度提升5倍，存储成本降低30%。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-4': [{"author":"刘磊","title":"IDS部署位置策略","content":"IDS应部署在服务器区入口、核心交换机镜像端口、DMZ区域。不要只放在互联网出口，内网横向移动才是最危险的。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"Suricata vs Snort","content":"Suricata多线程性能优，Snort社区规则更丰富。建议Suricata做检测引擎+Snort规则做补充，两者互补。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"孙婷","title":"告警研判工作流","content":"标准SOP：L1初筛→确认是否为真实攻击→L2深入分析→确定攻击阶段→L3溯源。checklist减少个人经验依赖。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-5': [{"author":"黄敏","title":"UEBA落地的数据前提","content":"算法不是瓶颈，数据质量才是。日志不全或不规范，行为基线就是垃圾进垃圾出。先做好日志治理再上AI。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"从规则到智能分析","content":"规则检测覆盖率约30%，加UEBA可达60-70%。但AI替代不了分析师——机器初筛，人决策，人机结合效果最好。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"周明","title":"异常检测误报治理","content":"UEBA初期误报率90%很正常。建立反馈闭环：标记误报→模型调整，三个月持续优化后能降到30%以下。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-6': [{"author":"孙婷","title":"事件分级业务对齐","content":"技术视角的高危不等于业务视角的紧急。定级标准必须和业务部门共定，明确每级对应的业务影响和损失后果。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"事件管理平台选型","content":"TheHive+Cortex是开源事件管理好组合，TheHive管理生命周期，Cortex做自动化分析。商业方案推荐ServiceNow SIR。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"刘磊","title":"事件报告编写要诀","content":"好的报告回答三个问题：发生了什么、影响了什么、如何防再发生。要让管理层看懂并做出决策。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-7': [{"author":"陈琳","title":"勒索软件响应实战","content":"一次勒索事件中攻击者从入侵到部署用了3天。如果有横向移动告警和及时遏制，损失可减少80%。响应速度第一位。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"应急响应工具箱","content":"必备：取证(FTK Imager/Velociraptor)、内存分析(Volatility)、日志(Chainsaw/Hayabusa)、网络(Wireshark)。提前备好不手忙脚乱。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"周明","title":"演练比文档更重要","content":"文档写得再好不演练等于废纸。每季度桌面推演，每年全流程实战演练。演练后必须复盘更新预案。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-8': [{"author":"刘磊","title":"防火墙规则治理","content":"规则超200条就难管理了。建议每季度做规则审计——清理过期、合并冗余。引入Tufin/Algosec可大幅提效。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"iptables到nftables","content":"nftables语法更简洁性能更好，是新项目首选。存量系统逐步迁移。nftables的set匹配能大幅减少规则数量。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"黄敏","title":"云防火墙vs传统防火墙","content":"云安全组是虚拟防火墙但功能有限。建议云WAF+安全组+第三方虚拟防火墙三层防护应对复杂云上安全需求。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-9': [{"author":"陈琳","title":"WAF误报治理","content":"部署第一周误报率可能超60%。建议先开log-only运行两周，分析误报特征调整规则再切拦截模式。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"ModSecurity性能","content":"默认规则全开性能损耗约30%。SQL注入/XSS规则必开，协议异常可放宽，国别规则按需开启。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"周明","title":"下一代WAF趋势","content":"新WAF引入ML检测但不能替代规则引擎。建议叠加：规则做确定性拦截，ML做异常检测补充。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-10': [{"author":"刘磊","title":"从VPN到零信任","content":"传统VPN认证通过就能访问整个内网风险太大。零信任架构：每应用独立认证、持续验证、最小授权。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"WireGuard实测","content":"WireGuard比OpenVPN快30-50%配置更简单。生态还不够成熟但中小团队强烈推荐。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"黄敏","title":"网络分段落地方案","content":"至少分5区：DMZ、应用区、DB区、管理区、办公区。区间防火墙默认拒绝按需开放。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-11': [{"author":"周明","title":"告警质量提升","content":"IDS上线第一周每天可能上千告警。找20%规则做针对性调优，告警量可下降一个数量级。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"孙婷","title":"告警疲劳应对","content":"告警疲劳比漏报更危险。启用告警聚合、设置优先级、建立分析师轮岗制度，防止麻木。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"赵刚","title":"规则生命周期管理","content":"每季评估规则有效性：检测率低于1%的禁用，误报率>50%的调优，新攻击手法补充规则。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-12': [{"author":"刘磊","title":"DDoS防护方案","content":"中小站最经济方案：Cloudflare免费版+源站IP隐藏+CDN。预算充足上高防IP和清洗中心。关键是提前准备。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"DDoS组合拳","content":"SYN Cookie只缓解SYN Flood，对HTTP Flood没用。DDoS防护要CDN+WAF+防火墙+清洗的组合防御。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"黄敏","title":"DDoS应急预案","content":"预案要素：触发阈值(带宽>80%)、联系方式(ISP/云厂商)、切换流程(切高防IP)、降级方案、通知模板。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-13': [{"author":"陈琳","title":"DNS安全全景","content":"DNS是被忽视的攻击面。除了劫持和DDoS放大，DNS隧道也是数据外传手段。监控TXT记录大包和长域名。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"DNSSEC踩坑记","content":"配置错误会导致整个域名解析失败。先在测试域名验证，用DNSViz可视化信任链。DS记录配置是关键。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"周明","title":"DoH的利与弊","content":"DoH加密DNS防劫持但让企业监控困难。建议做SSL解密+DNS日志外发，或使用内部DoH服务器。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-14': [{"author":"刘磊","title":"CDN隐藏源站","content":"除了DNS指向CDN，还要：防火墙只允许CDN IP回源、关闭源站直连端口、避免证书透明日志泄露源站。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"高可用分级策略","content":"不是所有系统都要双活。核心交易双活(RTO=0)、重要主备(RTO=1h)、一般冷备(RTO=24h)，大幅降成本。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"黄敏","title":"CDN WAF配置","content":"重点：O WASP Top10全开、封禁敏感路径(/admin)、启用Bot管理防爬虫和撞库、配置速率限制。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-15': [{"author":"陈琳","title":"批量安全加固","content":"手动加固100台服务器不现实。用Ansible Playbook+Puppet做批量，集成CIS Benchmark，每次变更后自动跑Lynis验证。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"SELinux实操","content":"别直接关SELinux。从Permissive模式开始，用audit2allow生成策略，逐步收紧。这是最后一道防线。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"周明","title":"服务器巡检清单","content":"周检必查：异常登录(lastb)、新增账户(passwd变更)、异常进程(ps aux)、异常连接(ss -tpln)、Crontab变更。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-16': [{"author":"刘磊","title":"AD攻击路径分析","content":"BloodHound一跑会发现大量到域管的高速公路。最危险：非特权用户对域管可写权限、Kerberoastable高权账户、无约束委派。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"PingCastle评分","content":"第一次跑23分的AD通过整改升到78分。主要整改：加强密码策略、精简域管组成员、强制SMB签名。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"孙婷","title":"AD持久化检测","content":"重点关注：黄金票据、白银票据、Skeleton Key、AdminSDHolder修改。用ATA或MDI监控这些操作。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-17': [{"author":"黄敏","title":"数据库四层防护","content":"网络层限制IP+认证层强密码MFA+权限层最小授权+审计层全记录。每层都要有监控告警。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"SQL注入全防护","content":"参数化查询是银弹但不万能。动态拼接时需严格验证+白名单过滤。ORM也会注入，Hibernate HQL注入常被忽略。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"陈琳","title":"数据库加密方案","content":"TDE性能好防不了DBA、列级加密灵活性能差、应用层加密最安全改造成本高。按数据敏感度选方案。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-18': [{"author":"周明","title":"容器安全左移","content":"Build阶段扫描镜像+Dockerfile检查，Deploy阶段准入控制，Run阶段运行时监控。左移可拦截80%安全问题。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"K8s安全三板斧","content":"Pod Security(禁privileged)+NetworkPolicy(默认拒绝)+RBAC(最小权限)。启用audit log接入SIEM。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"刘磊","title":"容器逃逸防护","content":"Never privileged、禁止挂载docker.sock、启用AppArmor/SELinux、只读rootfs、限制capabilities。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-19': [{"author":"黄敏","title":"云安全最大误区","content":"上云不等于安全。IaaS下用户负责OS以上安全。70%云安全事件是配置错误：S3公开、安全组全开、IAM过大。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"云安全审计工具","content":"Prowler覆盖CIS AWS全部检查项。ScoutSuite支持多云(AWS/Azure/GCP)同时审计。定期跑扫描。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"陈琳","title":"IAM最佳实践","content":"不用root日常操作、用户组授权非个人、用Roles不用Access Keys、定期审计未用权限、启用Access Analyzer。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-20': [{"author":"刘磊","title":"API攻击面","content":"现代应用80%流量是API，但安全重点在Web。OWASP API Top10列出BOLA等API特有风险，必须重视。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"JWT安全关键","content":"永远禁用none算法、HS256密钥至少256位、access token 15分钟、不在payload放敏感信息(base64非加密)。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"周明","title":"API网关能力","content":"认证OAuth2、授权RBAC、限流Rate Limit、WAF、审计、流量镜像。集中在网关层，避免每个服务重复实现。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-21': [{"author":"黄敏","title":"DevSecOps落地","content":"最大挑战不是工具是文化。把安全检查嵌入CI/CD、提供自助修复建议非只报漏洞、制定安全冠军计划。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"轻量威胁建模","content":"敏捷团队30分钟简化版：只做数据流图+Top5威胁分析。重大项目才做完整STRIDE。因团队而异灵活运用。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"陈琳","title":"开源SAST组合","content":"SonarQube做质量基线+SpotBugs+Semgrep自定义规则≈商业SAST的80%功能，零成本起步。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-22': [{"author":"周明","title":"等保2.0关键变化","content":"最大变化：扩展保护对象(云/物联网/工控)和强化主动防御。三级新增可信验证和态势感知要求，不是纯合规了。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"定级实战","content":"定高了成本剧增，定低了不合规。先评业务影响再参考同行案例。涉及大量个人信息的系统通常至少三级。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"孙婷","title":"测评常见扣分","content":"TOP5扣分：定期演练不足、密码策略不达标、日志保留<180天、制度不完善、缺集中管控。提前准备避坑。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-23': [{"author":"刘磊","title":"等保建设避坑","content":"三个坑：重技术轻管理(管理50分)、过度建设(买设备没人运营)、一次性整改不持续维护。建议分阶段推进。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"测评准备清单","content":"一个月前备：制度文件汇编、最新拓扑图、设备配置备份、角色访谈准备(各角色能说清安全职责)、设备运行正常。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"黄敏","title":"云等保特殊要求","content":"明确云厂商责任边界、用云合规包自查、数据存储在中国境内、测评机构需云等保测评资质。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-24': [{"author":"陈琳","title":"风险评估误区","content":"风险评估一次性做完没用。威胁在变、资产在变、脆弱性在变。每季度轻量评估+每年全面评估。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"风险量化FAIR","content":"高中低太模糊，管理层难决策。引入FAIR用经济损失描述风险：'可能造成X万元损失，年概率Y%'。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"周明","title":"风险处置优先级","content":"按风险值×处置难度排序：风险高+易修复优先、风险低+修复难的接受。投入产出比最优。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-25': [{"author":"刘磊","title":"备份验证教训","content":"曾因备份损坏无法恢复。之后建立每周自动恢复测试库验证完整性的机制。不做验证的备份等于没有备份。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"RPO/RTO设定","content":"不是越短越好要匹配业务。交易系统RPO=0，报表系统RPO=24h可以。和业务方确认写入SLA不拍脑袋。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"黄敏","title":"演练唯一标准","content":"BCP文档厚厚一叠从不演练，出事会发现：联系人电话换了、步骤不完整、恢复时间远超预期。半年一次底线。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-26': [{"author":"孙婷","title":"制度落地关键","content":"不执行等于零。关键：制度简洁明了+系统强制控制+新人培训必讲+违规有惩处。奖惩分明养成安全习惯。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"从合规到安全文化","content":"真正安全文化：员工主动报告可疑、开发写代码想安全、管理层决策纳入安全考量。长期培养而非一朝一夕。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"陈琳","title":"制度评审周期","content":"至少年度评审。触发更新：重大事件整改措施、新法规(个保法)、组织架构调整、新技术(AI)。过期制度失去权威。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-27': [{"author":"周明","title":"钓鱼演练数据","content":"首测点击率30-40%，3次演练+培训后降5%以下。但总有5%高危人群每次点，需重点辅导+额外培训。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"创新安全培训","content":"PPT宣讲效果差。尝试：模拟钓鱼、情景短剧、真实案例分享、知识竞赛。让培训有趣才有记忆点。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"刘磊","title":"社攻全面防御","content":"除邮件钓鱼还有：电话冒充IT、USB掉落攻击、尾随进入。社会工程防御要在培训中全面覆盖。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-28': [{"author":"黄敏","title":"红蓝对抗黄金规则","content":"首要原则安全——不能影响生产。必须约定：攻击范围、时间窗口、允许手法(是否社工)、紧急停止信号。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"从对抗到协作","content":"好对抗不是红队赢蓝队输，而是红队发现盲区蓝队改进检测。形成改进清单纳入安全建设计划。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"陈琳","title":"紫队融合新模式","content":"紫队(Purple Team)：红队展示攻击，蓝队当场调规则实时验证。半天紫队效果超过一月传统红蓝对抗。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-29': [{"author":"周明","title":"情报价值判断","content":"好情报有上下文(不仅是IOC)、有TTP(攻击手法)、适用你的行业。开源+1-2个商业源是最佳性价比组合。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"IOC到TTP进阶","content":"IOC变化快有效期短。成熟团队关注TTP——攻击者行为模式不会轻易改变。从IOC消费到TTP分析是进阶之路。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"刘磊","title":"情报驱动防御","content":"情报不应只是参考信息。某行业遭特定勒索→更新规则→检查攻击入口→加固系统。这才是情报驱动。","url":"https://www.freebuf.com/articles/es/278934.html"}],
        'def-30': [{"author":"孙婷","title":"SOC建设常见坑","content":"三个坑：人员不到位买设备、追求告警数量不关注质量、没有运营指标。从3-5人小团队起步聚焦核心场景。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"赵刚","title":"运营指标体系","content":"效率(MTTD/MTTR)、效果(检出率/覆盖率)、能力(分析师技能矩阵)、资源(工具覆盖率/自动化率)四维度KPI。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"黄敏","title":"SOC的未来-SOAR","content":"从简单场景自动化开始：钓鱼邮件处置、恶意IP封禁、告警富化。使L1工作自动化，让分析师做威胁狩猎。","url":"https://www.freebuf.com/articles/es/278934.html"}],
    }
    return notes[day_id]

# ===== 生成随堂测验Q2-Q5 =====
def gen_quiz(day_id):
    quizzes = {
        'def-1': [{"question":"MSSP指的是什么？","options":["A. 自建SOC","B. 托管安全服务提供商","C. 虚拟SOC","D. 政府安全机构"],"correctIndex":1,"explanation":"MSSP(Managed Security Service Provider)为组织提供外包安全运营服务。"},{"question":"SOC分析师L1的主要职责是？","options":["A. 威胁狩猎","B. 告警初筛和分类","C. 漏洞挖掘","D. 架构设计"],"correctIndex":1,"explanation":"L1负责告警初筛，将真实威胁升级给L2/L3深入分析。"},{"question":"以下哪项是SOC的核心技术平台？","options":["A. ERP系统","B. SIEM平台","C. CRM系统","D. 邮件服务器"],"correctIndex":1,"explanation":"SIEM(安全信息和事件管理)是SOC汇聚和分析安全数据的核心平台。"},{"question":"SOC通常采用什么工作制度？","options":["A. 朝九晚五","B. 7×24小时轮班","C. 项目制","D. 外包兼职"],"correctIndex":1,"explanation":"Gartner定义的SOC需要7×24小时持续监控，通常采用多班轮转制度。"}],
        'def-2': [{"question":"Windows中记录登录失败事件的日志类型是？","options":["A. Application","B. System","C. Security","D. Setup"],"correctIndex":2,"explanation":"Windows Security日志记录安全事件，包括登录成败(4624/4625)。"},{"question":"Linux系统认证日志存放在哪个文件？","options":["A. /var/log/messages","B. /var/log/auth.log","C. /var/log/syslog","D. /var/log/kern.log"],"correctIndex":1,"explanation":"/var/log/auth.log记录认证相关事件，包括SSH登录和sudo操作。"},{"question":"Filebeat在ELK架构中的作用是？","options":["A. 数据存储","B. 数据采集","C. 数据可视化","D. 告警通知"],"correctIndex":1,"explanation":"Filebeat是轻量级日志采集器，负责读取日志文件并发送到Logstash或Elasticsearch。"},{"question":"日志集中化最大的好处是什么？","options":["A. 节省存储空间","B. 便于跨系统关联分析","C. 加快网络速度","D. 自动修复漏洞"],"correctIndex":1,"explanation":"集中化使跨系统的安全事件关联分析成为可能，便于发现复杂攻击链。"}],
        'def-3': [{"question":"ELK中Kibana的主要功能是？","options":["A. 日志存储","B. 日志采集","C. 数据可视化","D. 告警通知"],"correctIndex":2,"explanation":"Kibana是ELK的可视化层，提供图表、仪表盘和数据探索等功能。"},{"question":"Elasticsearch默认API端口是多少？","options":["A. 3306","B. 9200","C. 6379","D. 8080"],"correctIndex":1,"explanation":"ES默认REST API端口是9200，集群内部通信端口是9300。"},{"question":"Logstash在ELK中的角色是？","options":["A. 数据存储","B. 数据处理管道","C. 可视化展现","D. 代理采集"],"correctIndex":1,"explanation":"Logstash负责日志的解析、过滤、转换和转发，是ELK的数据处理中枢。"},{"question":"SIEM告警规则的核心作用是？","options":["A. 压缩日志文件","B. 定义危险条件并触发通知","C. 加密网络流量","D. 加速搜索速度"],"correctIndex":1,"explanation":"告警规则定义了哪些日志组合构成安全事件，匹配后触发通知。"}],
        'def-4': [{"question":"Suricata相比Snort的主要优势是什么？","options":["A. 完全免费","B. 多线程和硬件加速","C. 不需要规则","D. 只能检测不能防御"],"correctIndex":1,"explanation":"Suricata支持多线程，利用GPU硬件加速，大流量场景性能优于Snort。"},{"question":"IDS旁路(镜像)部署的特点是什么？","options":["A. 可主动阻断攻击","B. 不影响生产流量但只能被动检测","C. 既检测又阻断","D. 只能检测病毒"],"correctIndex":1,"explanation":"旁路模式通过端口镜像获取流量副本，不参与实际转发，只能检测不能阻断。"},{"question":"Emerging Threats(ET)是什么？","options":["A. 威胁情报厂商","B. 开源IDS/IPS规则集","C. 漏洞数据库","D. 渗透测试工具"],"correctIndex":1,"explanation":"ET( Emerging Threats)是Proofpoint维护的开源IDS/IPS规则集，与Snort/Suricata兼容。"},{"question":"IDS规则中content字段的作用是？","options":["A. 指定协议类型","B. 匹配数据包中的具体内容","C. 设置告警级别","D. 定义响应动作"],"correctIndex":1,"explanation":"content字段匹配数据包具体内容，如'Failed password'检测SSH暴力破解。"}],
        'def-5': [{"question":"UEBA的全称是什么？","options":["A. Unified Endpoint Backup Appliance","B. User and Entity Behavior Analytics","C. Universal Event Bus Architecture","D. User Experience Based Authentication"],"correctIndex":1,"explanation":"UEBA(User and Entity Behavior Analytics)通过分析用户和实体行为发现异常。"},{"question":"建立用户行为基线通常需要多长时间的数据？","options":["A. 1小时","B. 至少2-4周","C. 实时数据即可","D. 不需要历史数据"],"correctIndex":1,"explanation":"行为基线需要足够长（通常2-4周）的历史数据才能准确刻画正常行为模式。"},{"question":"Isolation Forest属于哪种机器学习算法类型？","options":["A. 分类算法","B. 异常检测算法","C. 回归算法","D. 聚类算法"],"correctIndex":1,"explanation":"Isolation Forest(隔离森林)是基于集成学习的无监督异常检测算法。"},{"question":"异常检测的常见分析指标不包括？","options":["A. 登录时间","B. 访问频率","C. CPU温度","D. 数据下载量"],"correctIndex":2,"explanation":"CPU温度属于系统监控指标，不属于UEBA关注的行为分析维度。"}],
        'def-6': [{"question":"勒索软件攻击通常定为什么级别？","options":["A. 低危","B. 中危","C. 高危","D. 紧急"],"correctIndex":3,"explanation":"勒索软件可导致全局业务中断数据加密，需最高优先级响应，定为紧急级别。"},{"question":"安全事件定级最重要的依据是什么？","options":["A. 攻击者来源IP","B. 对业务的影响程度","C. 使用的攻击工具","D. 告警的发出时间"],"correctIndex":1,"explanation":"事件定级核心看对业务的影响程度——影响越大范围越广级别越高。"},{"question":"安全事件报告最核心的内容是什么？","options":["A. 报告封面设计","B. 事件时间线和处置过程","C. 公司简介","D. 攻击者个人信息"],"correctIndex":1,"explanation":"完整的时间线和处置过程便于复盘分析和经验总结，是报告的核心价值。"},{"question":"按来源分类，安全事件不包括哪类？","options":["A. 外部攻击","B. 内部威胁","C. 合作伙伴","D. 天气灾害"],"correctIndex":2,"explanation":"安全事件按来源分外部攻击、内部威胁和合作伙伴威胁，天气属于物理灾难范畴。"}],
        'def-7': [{"question":"PDCERF模型中遏制(Containment)阶段最核心的动作是？","options":["A. 通知媒体","B. 隔离受影响系统","C. 重装操作系统","D. 购买新设备"],"correctIndex":1,"explanation":"遏制的核心是隔离受影响系统，阻止损害扩大和攻击者横向移动。"},{"question":"PDCERF中根除(Eradication)阶段的目标是？","options":["A. 临时隔离","B. 彻底清除威胁并修复漏洞","C. 编写报告","D. 通知用户"],"correctIndex":1,"explanation":"根除阶段需要彻底删除恶意代码、修复被利用的漏洞、确认威胁已清除。"},{"question":"应急响应准备阶段最重要的产出是什么？","options":["A. 采购设备清单","B. 应急预案和响应团队联系方式","C. 年度财务报告","D. 产品说明书"],"correctIndex":1,"explanation":"准备阶段需制定应急预案、确定响应团队成员及沟通机制、准备工具资源。"},{"question":"恢复(Recover)阶段完成后还需要做什么？","options":["A. 直接结束","B. 持续监控验证系统恢复正常","C. 删除所有文档","D. 不做任何处理"],"correctIndex":1,"explanation":"恢复后需监控验证业务正常、系统无异常后再进入总结归档阶段。"}],
        'def-8': [{"question":"iptables中INPUT链控制什么流量？","options":["A. 转发的数据包","B. 目标地址是本机的入站数据包","C. 从本机发出的数据包","D. NAT转换的数据包"],"correctIndex":1,"explanation":"INPUT链处理目标是本机的入站包；OUTPUT处理本机发出；FORWARD处理转发包。"},{"question":"iptables中ESTABLISHED状态的作用是什么？","options":["A. 允许新连接","B. 允许已建立和关联连接的响应数据","C. 拒绝所有连接","D. 记录日志"],"correctIndex":1,"explanation":"ESTABLISHED,RELATED允许已建立连接和关联数据通过，无需重复验证。"},{"question":"iptables -t nat表的主要功能是？","options":["A. 过滤数据包","B. 网络地址转换","C. 修改数据包TTL","D. 记录日志"],"correctIndex":1,"explanation":"NAT表负责源地址转换(SNAT/MASQUERADE)和目的地址转换(DNAT/REDIRECT)。"},{"question":"iptables默认策略设为DROP后必须做什么？","options":["A. 什么都不做","B. 用ACCEPT规则放行必要服务端口","C. 删除所有规则","D. 重启服务器"],"correctIndex":1,"explanation":"默认DROP所有入站被拒绝，必须显式用ACCEPT放行SSH、HTTP等必要服务端口。"}],
        'def-9': [{"question":"WAF旁路模式如何工作？","options":["A. 拦截所有流量","B. 镜像流量检测但不阻断","C. 加密所有流量","D. 加速网站访问"],"correctIndex":1,"explanation":"旁路模式通过端口镜像获取流量副本，只检测不阻断，对业务零影响。"},{"question":"OWASP CRS的全称是什么？","options":["A. Cloud Resource System","B. Core Rule Set(核心规则集)","C. Cross Reference System","D. Content Rating Service"],"correctIndex":1,"explanation":"OWASP Core Rule Set为ModSecurity等WAF引擎提供全面的Web攻击检测规则集。"},{"question":"WAF部署初期产生大量误报时应该怎么做？","options":["A. 立即关闭WAF","B. 先开log-only模式，分析误报调整规则后再切拦截","C. 更换WAF品牌","D. 忽略所有告警"],"correctIndex":1,"explanation":"建议先开检测模式(log only)分析误报特征，调优规则后再切换到拦截模式。"},{"question":"ModSecurity是哪个组织的项目？","options":["A. Apache Foundation","B. Trustwave → OWASP","C. Nginx","D. Cloudflare"],"correctIndex":1,"explanation":"ModSecurity最初由Trustwave开发，后被OWASP组织接管维护。"}],
        'def-10': [{"question":"零信任安全模型的核心原则是什么？","options":["A. 信任但验证","B. 永不信任，始终验证","C. 信任内部，怀疑外部","D. 完全信任所有设备"],"correctIndex":1,"explanation":"零信任核心理念：不信任任何网络、设备或用户，每次访问都要重新验证授权。"},{"question":"DMZ区域通常放置什么类型的服务？","options":["A. 核心数据库","B. 对外提供服务的Web/Mail/DNS","C. 域控制器","D. HR管理系统"],"correctIndex":1,"explanation":"DMZ(非军事区)放置需要对外提供服务的服务器，隔离内外网访问。"},{"question":"OpenVPN默认使用什么端口和协议？","options":["A. TCP 80","B. TCP 443","C. UDP 1194","D. UDP 53"],"correctIndex":2,"explanation":"OpenVPN默认端口1194(UDP)，也可配置为TCP 443以绕过防火墙限制。"},{"question":"SSL VPN相比IPSec VPN的主要优势是？","options":["A. 速度更快","B. 对防火墙和NAT设备友好","C. 完全免费","D. 不需要证书"],"correctIndex":1,"explanation":"SSL VPN使用HTTPS(443端口)，通常不会被防火墙拦截，部署更便捷。"}],
        'def-11': [{"question":"IDS的False Positive(误报)是指？","options":["A. 真实攻击被正确检测","B. 正常流量错误标记为攻击","C. 真实攻击未被检测到","D. 规则未生效"],"correctIndex":1,"explanation":"False Positive(误报)将正常流量标记为攻击，大量误报导致告警疲劳。"},{"question":"减少IDS误报最直接有效的方法是？","options":["A. 关闭IDS","B. 将可信源IP加入排除列表","C. 增加更多检测规则","D. 降低日志级别"],"correctIndex":1,"explanation":"排除可信来源IP(如安全扫描器、监控系统)可快速减少大量已知来源误报。"},{"question":"IDS规则中threshold的作用是什么？","options":["A. 提高检测精度","B. 控制告警触发频率和阈值","C. 加快检测速度","D. 降低内存消耗"],"correctIndex":1,"explanation":"threshold控制规则触发条件，如'count 5, seconds 60'表示60秒内5次才告警。"},{"question":"IDS/IPS性能优化主要通过什么方式？","options":["A. 关闭所有规则","B. 规则分组、预处理优化和硬件加速","C. 重启设备","D. 增加更多网卡"],"correctIndex":1,"explanation":"通过规则合理分组、预处理流程优化和硬件加速来提升检测性能和吞吐量。"}],
        'def-12': [{"question":"SYN Flood攻击利用了什么协议漏洞？","options":["A. UDP无连接特性","B. TCP三次握手不完全连接","C. ICMP重定向","D. DNS递归查询"],"correctIndex":1,"explanation":"SYN Flood发送大量SYN但不完成三次握手，耗尽服务器半连接队列资源。"},{"question":"黑洞路由(Blackhole)的主要作用是什么？","options":["A. 加速流量转发","B. 将攻击流量直接丢弃","C. 加密传输数据","D. 实现负载均衡"],"correctIndex":1,"explanation":"黑洞路由将目标IP的流量全部丢弃，是最直接但粗暴的DDoS应急手段。"},{"question":"以下哪个不是DDoS防护手段？","options":["A. CDN分散攻击流量","B. 清洗中心过滤恶意流量","C. 增加防火墙规则条数","D. Anycast就近路由"],"correctIndex":2,"explanation":"单纯增加防火墙规则不能有效防护DDoS，需CDN+清洗中心+Anycast等专门手段。"},{"question":"开启TCP SYN Cookie后服务器的变化是什么？","options":["A. 不需要任何验证","B. 收到SYN时不立即分配连接资源","C. 完全拒绝所有SYN请求","D. 只允许已认证用户"],"correctIndex":1,"explanation":"SYN Cookie使服务器收到SYN时用Cookie验证客户端，验证通过后才分配资源。"}],
        'def-13': [{"question":"DNS放大攻击主要利用什么类型的DNS记录？","options":["A. A记录","B. MX记录","C. ANY/TXT等大响应记录","D. CNAME记录"],"correctIndex":2,"explanation":"攻击者利用ANY/TXT等大响应记录，用小请求触发大响应实现流量放大。"},{"question":"DNSSEC解决的核心安全问题是？","options":["A. DNS查询速度","B. DNS响应的完整性和真实性","C. DNS缓存过期","D. DNS服务器配置"],"correctIndex":1,"explanation":"DNSSEC通过数字签名验证DNS响应，防止DNS欺骗和缓存投毒攻击。"},{"question":"DNS over HTTPS(DoH)使用什么端口？","options":["A. 53","B. 853","C. 443","D. 8080"],"correctIndex":2,"explanation":"DoH通过HTTPS(443端口)封装DNS查询，使DNS流量与普通HTTPS流量混合难以识别。"},{"question":"DNS隧道攻击最明显的特征是什么？","options":["A. 频繁的A记录查询","B. 异常长的DNS查询域名","C. MX记录查询增多","D. PTR反向查询"],"correctIndex":1,"explanation":"DNS隧道通过异常长域名(如base64编码的外泄数据)在DNS查询中隐蔽传输。"}],
        'def-14': [{"question":"使用CDN隐藏源站IP最基本的做法是什么？","options":["A. 加密所有通信","B. 将域名DNS解析指向CDN提供的CNAME","C. 关闭源站服务器","D. 使用VPN连接"],"correctIndex":1,"explanation":"将DNS解析指向CDN的CNAME，用户直接访问CDN边缘节点，源站IP对外不可见。"},{"question":"Anycast技术如何帮助抗DDoS？","options":["A. 加密攻击流量","B. 将攻击流量分散到多个地理节点","C. 永久封锁攻击者","D. 溯源攻击者身份"],"correctIndex":1,"explanation":"Anycast将同一IP宣告到多个地理位置，攻击流量自动分散到最近节点降低单点压力。"},{"question":"高可用架构设计的核心思想是什么？","options":["A. 使用最高配置的设备","B. 消除单点故障(SPOF)","C. 减少功能模块","D. 降低运维成本"],"correctIndex":1,"explanation":"高可用通过多节点和链路冗余消除单点故障，确保单组件失效不影响整体服务。"},{"question":"CDN的Always Use HTTPS配置的作用是？","options":["A. 可选设置","B. 强制将所有HTTP请求301跳转到HTTPS","C. 仅加速HTTPS连接","D. 禁用HTTPS功能"],"correctIndex":1,"explanation":"开启后所有HTTP访问自动重定向到HTTPS，防止明文传输导致的中间人攻击和信息泄露。"}],
        'def-15': [{"question":"Linux中SSH服务默认监听哪个端口？","options":["A. 21","B. 22","C. 23","D. 80"],"correctIndex":1,"explanation":"SSH默认监听22端口，安全加固时建议修改为非标准端口减少自动化扫描。"},{"question":"/etc/shadow文件的推荐权限设置是？","options":["A. 777","B. 644","C. 600","D. 400"],"correctIndex":2,"explanation":"/etc/shadow存放密码哈希必须设为600仅root可读写防止密码哈希泄露。"},{"question":"Linux中禁用root直接SSH登录的配置项是？","options":["A. AllowRootLogin yes","B. PermitRootLogin no","C. RootLogin permit","D. NoRootLogin true"],"correctIndex":1,"explanation":"PermitRootLogin no禁用root直接SSH登录，迫使用户用普通账户再sudo提权。"},{"question":"CIS Benchmark是什么？","options":["A. 编程竞赛标准","B. 各操作系统安全配置基线指南","C. 网络协议规范","D. 加密算法标准"],"correctIndex":1,"explanation":"CIS(Center for Internet Security)发布各OS安全配置基线，是全球公认的加固参考标准。"}],
        'def-16': [{"question":"BloodHound主要用于什么目的？","options":["A. 漏洞扫描","B. Active Directory攻击路径分析","C. 代码安全审计","D. 网络流量监控"],"correctIndex":1,"explanation":"BloodHound分析AD中的权限关系，可视化展示从普通用户到域管的所有攻击路径。"},{"question":"Windows中禁用SMBv1协议的主要原因是什么？","options":["A. 协议传输速度慢","B. 存在永恒之蓝等严重远程漏洞","C. 不支持文件加密","D. 占用过多网络带宽"],"correctIndex":1,"explanation":"SMBv1存在EternalBlue等严重漏洞，是WannaCry等勒索病毒传播的主要途径。"},{"question":"Protected Users组提供了什么保护？","options":["A. 文件系统加密","B. 防止凭据缓存和哈希传递攻击","C. 加速域登录速度","D. 自动分配管理权限"],"correctIndex":1,"explanation":"Protected Users成员不缓存明文密码、不存储NTLM哈希、禁用Kerberos DES加密。"},{"question":"LAPS(Local Administrator Password Solution)解决什么问题？","options":["A. 用户密码管理","B. 本地管理员密码集中管理和定期轮换","C. 域用户权限管理","D. 文件共享安全"],"correctIndex":1,"explanation":"LAPS确保每台机器有唯一的本地管理员密码并定期自动轮换，防止密码复用横向移动。"}],
        'def-17': [{"question":"数据库安全中最小权限原则体现在哪里？","options":["A. 所有用户使用root账户","B. 每个账户仅授予完成工作所需的最小权限","C. 每天备份一次数据库","D. 使用SSL加密通信"],"correctIndex":1,"explanation":"最小权限原则要求每个数据库账户只拥有完成其任务所需的最小权限集合。"},{"question":"为什么参数化查询能有效防止SQL注入？","options":["A. 对查询语句进行加密","B. 将用户输入与SQL代码逻辑完全分离","C. 过滤所有特殊字符","D. 限制每秒查询次数"],"correctIndex":1,"explanation":"参数化查询中用户数据永远被当作值而不是SQL代码，从根本上防止注入。"},{"question":"MySQL审计插件(Audit Plugin)的主要作用是？","options":["A. 加速查询性能","B. 记录所有数据库操作供安全审计","C. 自动备份数据","D. 优化索引结构"],"correctIndex":1,"explanation":"审计插件记录连接、查询、增删改等所有操作，用于安全事件追踪和法规合规。"},{"question":"数据库备份文件加密的主要目的是什么？","options":["A. 减少备份文件大小","B. 防止备份介质丢失或被盗后数据泄露","C. 加快备份恢复速度","D. 便于备份文件分类管理"],"correctIndex":1,"explanation":"备份文件若被攻击者获取，加密确保数据不会被直接读取利用。"}],
        'def-18': [{"question":"Docker容器中使用非root用户运行的主要目的是？","options":["A. 符合法规要求","B. 减少容器逃逸后对宿主机的权限影响","C. 提高应用运行速度","D. 节约系统资源"],"correctIndex":1,"explanation":"以root运行的容器逃逸后攻击者直接获得宿主机root权限，非root可限制损害范围。"},{"question":"Trivy工具的主要功能是什么？","options":["A. 容器编排管理","B. 容器镜像和文件系统漏洞扫描","C. 代码格式自动修复","D. 日志集中收集"],"correctIndex":1,"explanation":"Trivy是Aqua Security开源的漏洞扫描器，支持镜像、Git仓库和文件系统扫描。"},{"question":"Docker只读文件系统(readOnly rootfs)的好处是什么？","options":["A. 提高容器启动速度","B. 防止攻击者在容器内写入恶意文件","C. 节省磁盘空间","D. 方便开发调试"],"correctIndex":1,"explanation":"只读根文件系统阻止攻击者写入恶意脚本或修改系统配置增强容器安全性。"},{"question":"Falco监控的主要目标是什么？","options":["A. 网络带宽使用情况","B. 容器和内核运行时的异常系统调用","C. 代码编译错误","D. 磁盘IO性能"],"correctIndex":1,"explanation":"Falco通过内核eBPF监控容器异常行为，如权限提升、文件篡改和网络连接。"}],
        'def-19': [{"question":"云安全责任共担模型中SaaS模式用户负责什么？","options":["A. 物理服务器安全","B. 虚拟化平台安全","C. 应用配置和身份管理","D. 网络基础设施"],"correctIndex":2,"explanation":"SaaS用户仅负责数据和身份管理，其余安全责任由云服务商承担。"},{"question":"CSPM的全称是什么？","options":["A. Cloud Service Provider Management","B. Cloud Security Posture Management","C. Cloud Storage Performance Monitor","D. Cloud Software Package Manager"],"correctIndex":1,"explanation":"CSPM(Cloud Security Posture Management)持续评估和管理云的配置合规和安全态势。"},{"question":"AWS S3数据泄露最常见的原因是什么？","options":["A. AWS基础设施被黑客攻破","B. 用户将S3存储桶错误配置为公开访问","C. DDoS攻击导致数据泄露","D. 服务端加密算法被破解"],"correctIndex":1,"explanation":"配置错误(S3 Bucket Public)是云数据泄露的首要原因，全球已发生多起重大事件。"},{"question":"CWPP的主要保护对象是什么？","options":["A. 网络交换设备","B. 云上的虚拟机/容器/无服务器等工作负载","C. IAM用户和角色","D. DNS域名服务"],"correctIndex":1,"explanation":"CWPP(Cloud Workload Protection Platform)为云上各类工作负载提供全生命周期安全防护。"}],
        'def-20': [{"question":"OWASP API Security Top 10中排名第一的风险是？","options":["A. 注入攻击","B. 失效的对象级授权(BOLA)","C. 缺乏资源和速率限制","D. 安全配置错误"],"correctIndex":1,"explanation":"BOLA(Broken Object Level Authorization)是API最常见风险——通过篡改对象ID访问未授权资源。"},{"question":"JWT安全使用中最重要的原则是？","options":["A. 使用none签名算法","B. 设置短期有效期并使用强密钥","C. 在payload中存放密码","D. 使用HTTP传输Token"],"correctIndex":1,"explanation":"JWT必须使用强密钥(HS256≥256bit)、短暂有效期(如15分钟)、不在payload放敏感信息。"},{"question":"API Rate Limiting(限流)的主要作用是？","options":["A. 加速API响应","B. 限制单位时间请求次数防滥用","C. 加密API通信","D. 缓存API响应"],"correctIndex":1,"explanation":"限流防止API滥用、暴力破解、DDoS和撞库攻击，保护后端服务可用性。"},{"question":"API网关最重要的安全功能是？","options":["A. 服务发现","B. 统一认证授权和流量控制","C. 负载均衡","D. 域名解析"],"correctIndex":1,"explanation":"API网关作为所有API流量的统一入口，集中实现认证、授权、限流、监控等安全能力。"}],
        'def-21': [{"question":"STRIDE威胁模型中'S'代表什么威胁？","options":["A. 信息泄露","B. 拒绝服务","C. 伪装/欺骗","D. 篡改数据"],"correctIndex":2,"explanation":"S=Spoofing(伪装欺骗)，对应认证(Authentication)安全属性。"},{"question":"SAST(静态分析)和DAST(动态分析)的主要区别是什么？","options":["A. 没有本质区别","B. SAST分析源代码，DAST对运行中系统做黑盒测试","C. SAST更快","D. DAST更准确"],"correctIndex":1,"explanation":"SAST(白盒)直接分析源码发现编码问题，DAST(黑盒)模拟攻击测试运行中的应用。"},{"question":"SDL全称是什么？","options":["A. Software Design Language","B. Security Development Lifecycle","C. System Debug Log","D. Secure Data Layer"],"correctIndex":1,"explanation":"SDL(安全开发生命周期)将安全实践融入软件开发的每个阶段。"},{"question":"npm audit命令的作用是什么？","options":["A. 安装npm包","B. 扫描项目依赖中的已知安全漏洞","C. 运行单元测试","D. 编译TypeScript代码"],"correctIndex":1,"explanation":"npm audit自动检查项目直接和间接依赖中是否存在CVE已知漏洞并提供修复建议。"}],
        'def-22': [{"question":"等保2.0相比1.0新增加了哪些保护对象？","options":["A. 传统办公系统","B. 云计算/物联网/工控/大数据平台","C. 个人PC","D. 移动APP"],"correctIndex":1,"explanation":"等保2.0扩展覆盖了云计算平台、物联网、工业控制系统和大数据等新型信息系统。"},{"question":"等保三级的测评频率要求是什么？","options":["A. 终身只测一次","B. 每年至少一次","C. 每两年一次","D. 不需要测评"],"correctIndex":1,"explanation":"等保三级系统要求每年至少进行一次等级测评，二级系统为每两年一次。"},{"question":"等保2.0的核心国家标准编号是？","options":["A. ISO 27001:2013","B. GB/T 22239-2019","C. NIST SP 800-53","D. PCI DSS v4.0"],"correctIndex":1,"explanation":"GB/T 22239-2019《网络安全等级保护基本要求》是等保2.0的核心技术标准。"},{"question":"等保制度遵循的流程是？","options":["A. 测评→整改→定级→备案","B. 定级→备案→建设整改→测评→监督检查","C. 备案→建设→定级→测评","D. 直接实施安全措施即可"],"correctIndex":1,"explanation":"等保标准流程：系统定级→公安机关备案→差距分析和整改→测评机构测评→持续监督检查。"}],
        'def-23': [{"question":"等保差距分析的目标是什么？","options":["A. 发现系统中的所有漏洞","B. 对比现状和等保要求找出需整改项目","C. 评估系统性能瓶颈","D. 审计财务支出"],"correctIndex":1,"explanation":"差距分析通过现状与等保要求的对标，识别技术和管理两个维度的整改需求。"},{"question":"等保备案应该在哪个部门办理？","options":["A. 市场监管局","B. 设区的市级以上公安机关","C. 税务局","D. 通信管理局"],"correctIndex":1,"explanation":"根据《网络安全法》，信息系统定级后需到所在地市级以上公安机关备案。"},{"question":"等保建设整改包含哪些方面？","options":["A. 仅采购安全设备","B. 技术整改和管理制度完善两方面","C. 仅人员培训","D. 仅编写文档"],"correctIndex":1,"explanation":"等保整改包含技术整改(部署安全产品、安全配置)和管理整改(完善制度、流程和人员)。"},{"question":"等级测评必须由谁来完成？","options":["A. 单位内部安全团队","B. 公安部认可的第三方测评机构","C. 任意安全公司","D. 属地派出所"],"correctIndex":1,"explanation":"等级测评必须由经公安部认可的具有等级测评资质的第三方专业机构实施。"}],
        'def-24': [{"question":"风险评估基本公式是什么？","options":["A. 风险=威胁概率+脆弱性程度","B. 风险=资产价值×威胁可能性×脆弱性严重程度","C. 风险=资产价值÷威胁等级","D. 风险=威胁数+漏洞数"],"correctIndex":1,"explanation":"风险值=资产价值×威胁可能性×脆弱性严重程度，三个因素缺一不可。"},{"question":"风险处置策略中'缓解(Mitigation)'是指什么？","options":["A. 停止相关业务活动","B. 采取安全控制措施降低风险发生概率或影响","C. 购买网络安全保险","D. 完全忽略风险存在"],"correctIndex":1,"explanation":"缓解通过部署安全控制措施(如防火墙、加密)降低风险发生的可能性或影响程度。"},{"question":"残余风险必须由谁批准接受？","options":["A. 安全工程师个人决定","B. 组织管理层正式批准","C. 任何员工都可决定","D. 不需要任何人批准"],"correctIndex":1,"explanation":"残余风险需管理层书面接受，明确已知无法消除的风险及可能承担的后果。"},{"question":"风险评估中哪些不属于资产分类范畴？","options":["A. 硬件基础设施","B. 业务和数据资产","C. 员工私有个人财产","D. 软件和应用资产"],"correctIndex":2,"explanation":"风险评估关注组织IT资产(硬件/软件/数据/服务等)，不包括员工个人私有财产。"}],
        'def-25': [{"question":"RPO(Recovery Point Objective)衡量什么指标？","options":["A. 系统恢复所需的最长时间","B. 灾难后可接受的最大数据丢失时间","C. 备份操作频率","D. 服务器硬件配置"],"correctIndex":1,"explanation":"RPO定义灾难后可容忍的数据丢失窗口，RPO=1小时意味着最多丢失1小时数据。"},{"question":"备份3-2-1原则是什么意思？","options":["A. 3个部门2种方案1次演练","B. 至少3份备份、2种介质、1份异地","C. 每3天备份2次保留1年","D. 3个副本2个站点1套方案"],"correctIndex":1,"explanation":"3份备份(1份主+2份副本)、2种不同存储介质、其中1份存放在异地防区域性灾难。"},{"question":"灾难恢复方案中RTO最小(恢复最快)的是哪种？","options":["A. 冷备","B. 温备","C. 热备/双活","D. 无备份方案"],"correctIndex":2,"explanation":"热备/双活方案RTO通常在数分钟到1小时，是所有方案中恢复时间最短的。"},{"question":"桌面演练和全量演练的区别是什么？","options":["A. 完全相同","B. 桌面讨论流程步骤，全量是实际执行恢复操作","C. 桌面更快","D. 全量成本更低"],"correctIndex":1,"explanation":"桌面演练是纸上谈兵讨论流程，全量演练是实际操作执行完整的系统恢复。"}],
        'def-26': [{"question":"安全策略体系的最顶层是什么？","options":["A. 操作流程","B. 安全标准","C. 安全策略/方针","D. 配置基线"],"correctIndex":2,"explanation":"安全策略/方针定义了组织安全目标和基本原则，是体系的最高层文件。"},{"question":"安全制度的执行落地最重要的是什么？","options":["A. 打印漂亮的文档","B. 通过技术控制系统强制执行而非依赖自觉","C. 只在管理层宣传","D. 不检查也不考核"],"correctIndex":1,"explanation":"通过技术手段强制实施(如密码策略系统强制)比依靠员工自觉更可靠。"},{"question":"安全制度至少多久需要评审一次？","options":["A. 永不评审","B. 至少每年一次","C. 每五年一次","D. 只有出事时才评审"],"correctIndex":1,"explanation":"安全制度至少年度评审，重大事件、法规变更、组织调整时应即时触发更新。"},{"question":"ISO 27001标准主要关注什么方面？","options":["A. 产品开发流程","B. 信息安全管理体系(ISMS)","C. 网络设备配置","D. 数据中心建设"],"correctIndex":1,"explanation":"ISO 27001定义了建立、实施、维护和持续改进信息安全管理体系(ISMS)的要求。"}],
        'def-27': [{"question":"钓鱼邮件最典型的特征是什么？","options":["A. 精美的公司Logo","B. 制造紧迫感催促立即行动","C. 语法完美的正式文本","D. 来自内部邮箱"],"correctIndex":1,"explanation":"钓鱼邮件常用'紧急'、'账户锁定'、'立即验证'等紧迫感语言催促用户不经理智判断。"},{"question":"首次钓鱼演练通常的点击率是多少？","options":["A. 低于5%","B. 约30-40%","C. 高于80%","D. 几乎为零"],"correctIndex":1,"explanation":"多数组织首次钓鱼演练的邮件点击率在30-40%之间，说明安全意识普遍薄弱。"},{"question":"安全意识培训最有效的方式是什么？","options":["A. PPT宣讲","B. 模拟钓鱼演练+案例分享+场景互动","C. 发放安全手册","D. 强制观看安全视频"],"correctIndex":1,"explanation":"实战演练+真实案例+互动参与比被动接受式的PPT培训效果好得多。"},{"question":"Gophish平台的主要用途是什么？","options":["A. 漏洞扫描","B. 模拟钓鱼攻击演练测试员工安全意识","C. 网络流量分析","D. 恶意软件沙箱"],"correctIndex":1,"explanation":"Gophish是开源钓鱼演练平台，可创建仿真钓鱼邮件测试员工识别和报告能力。"}],
        'def-28': [{"question":"红蓝对抗中红队(Red Team)的目标是什么？","options":["A. 修复系统漏洞","B. 模拟真实攻击者获取目标系统的访问权限","C. 检测和响应攻击","D. 编写安全报告"],"correctIndex":1,"explanation":"红队模拟真实APT攻击者，通过各种手段尝试突破防线获取目标权限。"},{"question":"红蓝对抗的首要原则是什么？","options":["A. 尽可能多地破坏系统","B. 确保不影响生产系统正常运行","C. 不需要任何约定","D. 公开进行不保密"],"correctIndex":1,"explanation":"对抗必须在约定范围内安全进行，不能影响业务生产，约定紧急停止信号机制。"},{"question":"CTF竞赛一般分为哪些类型？","options":["A. 只有解题模式","B. Jeopardy(解题)、AWD(攻防)、混合模式","C. 只有攻防模式","D. 只有选择题模式"],"correctIndex":1,"explanation":"CTF竞赛包括Jeopardy解题赛、AWD攻防对抗赛和混合(RW)模式三种主要形式。"},{"question":"紫队(Purple Team)的工作模式是什么？","options":["A. 红队和蓝队各自独立","B. 红队展示攻击手法，蓝队当场调整检测规则实时验证","C. 只做蓝队防御","D. 只做红队攻击"],"correctIndex":1,"explanation":"紫队是红蓝协同演练模式——红队演示攻击、蓝队当场调整检测并验证，效率更高。"}],
        'def-29': [{"question":"IOC(Indicators of Compromise)指的是什么？","options":["A. 安全认证证书","B. 主机被入侵的痕迹指标","C. 入侵检测系统","D. 安全检查清单"],"correctIndex":1,"explanation":"IOC是安全事件中识别出的威胁指标，如恶意IP、域名、文件哈希、可疑URL等。"},{"question":"VirusTotal平台的主要功能是什么？","options":["A. 杀毒软件下载","B. 可疑文件和URL的多引擎扫描查询","C. 系统漏洞修补","D. 防火墙规则配置"],"correctIndex":1,"explanation":"VirusTotal用60+安全引擎同时扫描可疑文件/URL，是最常用的免费威胁查询平台。"},{"question":"威胁情报中TTP指的是什么？","options":["A. 网络传输协议","B. 攻击者的战术、技术和过程","C. 安全产品配置","D. 漏洞披露流程"],"correctIndex":1,"explanation":"TTP(Tactics, Techniques, Procedures)描述攻击者的行为模式和手法，比IOC更持久。"},{"question":"MISP平台主要用于什么场景？","options":["A. 漏洞扫描","B. 威胁情报的收集、存储和共享","C. 代码审计","D. 防火墙管理"],"correctIndex":1,"explanation":"MISP(Malware Information Sharing Platform)是开源威胁情报共享平台，支持IOC管理和交换。"}],
        'def-30': [{"question":"安全运营成熟度模型的最高级别是什么？","options":["A. 合规驱动","B. 被动响应","C. 主动检测","D. 自适应/智能化运营"],"correctIndex":3,"explanation":"成熟度最高级是自适应级(L5)，能根据威胁态势自动调整安全策略和检测规则。"},{"question":"SOAR在安全运营中的核心作用是什么？","options":["A. 存储安全日志","B. 安全编排、自动化和响应","C. 生成安全报表","D. 管理网络设备"],"correctIndex":1,"explanation":"SOAR(Security Orchestration Automation Response)将人、流程和技术编排自动化响应安全事件。"},{"question":"安全运营指标MTTD指的是什么？","options":["A. 平均恢复时间","B. 平均检测时间","C. 平均响应时间","D. 平均处理时间"],"correctIndex":1,"explanation":"MTTD(Mean Time to Detect)衡量从安全事件发生到被检测发现的平均时间。"},{"question":"安全运营建设最基本的三要素是什么？","options":["A. 预算、品牌、宣传","B. 人员、流程、技术","C. 硬件、软件、网络","D. 开发、测试、运维"],"correctIndex":1,"explanation":"安全运营体系建设需要人员(团队能力)、流程(制度规范)和技术(工具平台)三方面协同发展。"}],
    }
    return quizzes[day_id]

# ===== 原始重复字符串(用于查找替换) =====
OLD_CODE = 'codeExamples: [{"title":"动手实践","language":"python","code":"# 安全防御实践\\\\nprint(\\"安全运维与防御\\")\\\\nprint(\\"=\\"*40)\\\\n\\\\ndef security_baseline():\\\\n    checks = [\\\\n        (\\"防火墙\\", True),\\\\n        (\\"入侵检测\\", True),\\\\n        (\\"日志审计\\", False),\\\\n        (\\"访问控制\\", True),\\\\n    ]\\\\n    for name, status in checks:\\\\n        status_str = \\"OK\\" if status else \\"待改进\\"\\\\n        print(f\\"[{status_str}] {name}\\")\\\\n\\\\nsecurity_baseline()","explanation":"安全防御配置基线检查代码示例"}]'

OLD_NOTES = 'expertNotes: [{"author":"张伟","title":"安全防御体系建设","content":"安全防御不能只靠单一技术。纵深防御是核心原则——从网络边界到终端，从应用到数据，层层设防。安全产品需要持续的运营和优化。","url":"https://www.freebuf.com/articles/es/267825.html"},{"author":"李明","title":"安全运维实战经验","content":"安全运维的核心是持续监控+快速响应。建议建立安全基线和异常检测机制，对偏离基线的行为进行告警。自动化是提升效率的关键。","url":"https://www.anquanke.com/post/id/243567.html"},{"author":"王芳","title":"安全管理实践心得","content":"技术和管理要两手抓。再好的安全技术如果管理跟不上也是白搭。建议建立完善的安全管理制度、操作流程和应急预案。定期安全演练是检验能力的手段。","url":"https://www.freebuf.com/articles/es/278934.html"}]'

# Quiz Q2-Q5 old block (4 duplicate questions)
OLD_QUIZ_BLOCK = '{"question":"信息安全的三个基本要素是什么？","options":["机密性、完整性、可用性","机密性、认证性、可用性","完整性、认证性、可用性","机密性、完整性、认证性"],"correctIndex":0,"explanation":"CIA三要素：机密性、完整性、可用性。"},{"question":"纵深防御的核心原则是什么？","options":["只依赖防火墙","多层安全控制叠加","只做边界防护","依赖单一产品"],"correctIndex":1,"explanation":"纵深防御通过多层安全控制叠加保护系统。"},{"question":"安全事件应急响应第一步？","options":["修复漏洞","通知媒体","隔离受影响系统","重装系统"],"correctIndex":2,"explanation":"应急响应第一步是隔离受影响系统防止损害扩大。"},{"question":"以下哪项不是SOC的主要职能？","options":["安全监控","威胁检测","产品研发","事件响应"],"correctIndex":2,"explanation":"产品研发不属于SOC的安全运营核心职能。"}'

import json

def fmt_code(day_id):
    lang, code, expl = gen_code(day_id)
    # Escape properly
    code_escaped = code.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
    expl_escaped = expl.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
    return f'codeExamples: [{{"title":"动手实践","language":"{lang}","code":"{code_escaped}","explanation":"{expl_escaped}"}}]'

def fmt_notes(day_id):
    notes = gen_notes(day_id)
    parts = []
    for n in notes:
        parts.append(f'{{"author":"{n["author"]}","title":"{n["title"]}","content":"{n["content"]}","url":"{n["url"]}"}}')
    return 'expertNotes: [' + ','.join(parts) + ']'

def fmt_quiz(day_id):
    qs = gen_quiz(day_id)
    parts = []
    for q in qs:
        parts.append(json.dumps(q, ensure_ascii=False))
    return ','.join(parts)

# ===== 执行替换 =====
print("修复 cyberDefense.ts ...")
changes = 0

for i in range(1, 31):
    day_id = f'def-{i}'
    # Find day boundary
    idx = content.find(f"id: '{day_id}'")
    if idx == -1:
        print(f"  {day_id}: NOT FOUND!")
        continue
    # Find next day boundary or end
    next_pattern = f"id: 'def-{i+1}'" if i < 30 else "export const cyberDefensePlan"
    next_idx = content.find(next_pattern, idx + 10)
    if next_idx == -1:
        next_idx = len(content)
    
    day_chunk = content[idx:next_idx]
    
    # 1. Replace codeExamples
    new_code = fmt_code(day_id)
    if OLD_CODE in day_chunk:
        content = content[:idx] + day_chunk.replace(OLD_CODE, new_code) + content[next_idx:]
        day_chunk = content[idx:idx + len(day_chunk) - len(OLD_CODE) + len(new_code)]
        changes += 1
        print(f"  {day_id}: codeExamples OK")
    else:
        print(f"  {day_id}: codeExamples pattern not found (may be already fixed)")
    
    # 2. Replace expertNotes
    new_notes = fmt_notes(day_id)
    if OLD_NOTES in day_chunk:
        content = content[:idx] + day_chunk.replace(OLD_NOTES, new_notes) + content[next_idx:]
        day_chunk = content[idx:idx + len(day_chunk) - len(OLD_NOTES) + len(new_notes)]
        changes += 1
        print(f"  {day_id}: expertNotes OK")
    else:
        print(f"  {day_id}: expertNotes pattern not found")
    
    # 3. Replace quiz Q2-Q5
    if OLD_QUIZ_BLOCK in day_chunk:
        new_qs = fmt_quiz(day_id)
        content = content[:idx] + day_chunk.replace(OLD_QUIZ_BLOCK, new_qs) + content[next_idx:]
        day_chunk = content[idx:idx + len(day_chunk) - len(OLD_QUIZ_BLOCK) + len(new_qs)]
        changes += 1
        print(f"  {day_id}: quizQ2-Q5 OK")
    else:
        print(f"  {day_id}: quiz block pattern not found")

# ===== 写回文件 =====
with open(FPATH, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n总计修改: {changes} 处")
print("完成! 请验证文件。")
