# -*- coding: utf-8 -*-
"""Rewrite: Use list-of-lines approach to avoid ALL string escaping issues."""
import os
OUT = os.path.dirname(os.path.abspath(__file__))

L = lambda *args: list(args)  # lines helper

def write_md(day, lines_list):
    """Write a markdown file from a flat list of line strings."""
    fname = os.path.join(OUT, f'day-{day}.md')
    with open(fname, 'w', encoding='utf-8') as f:
        for line in lines_list:
            f.write(line + '\n')
    return len(lines_list)

# ============ DAY 29: ATT&CK + Kill Chain ============
d29 = L(
'---',
'day: 29',
'title: ATT&CK框架与Kill Chain模型——蓝队的"敌军战术手册"',
'phase: 第一阶段',
'difficulty: ⭐⭐ 基础',
'---',
'',
'# Day 29：ATT&CK框架与Kill Chain模型——蓝队的"敌军战术手册"',
'',
'> **阶段**：第一阶段 · 初级蓝队夯实 | **难度**：⭐⭐ 基础 | **预计课时**：2-3小时',
'',
'---',
'',
'## 📋 今日学习目标',
'',
'1. 理解ATT&CK框架的矩阵结构和导航方式',
'2. 掌握Kill Chain的7个攻击阶段',
'3. 学会从蓝队视角映射"检测点"到攻击链的每个环节',
'4. 能说出5个以上ATT&CK战术（Tactics）和对应技术（Techniques）',
'5. 理解为什么ATT&CK是蓝队最重要的知识框架之一',
'',
'---',
'',
'## 📖 核心知识讲解',
'',
'> 🧠 **白话理解**：ATT&CK框架就像一本"敌军战术手册"——列出了黑客从踩点到得手的所有套路。Kill Chain就是一条"攻击流水线"——每一步都是你可以拦截的关卡。把两者结合起来，你就知道"攻击者可能怎么来，我应该在哪个环节设防"。',
'',
'### 一、ATT&CK矩阵是什么——一张表看懂黑客的所有招式',
'',
'ATT&CK（Adversarial Tactics, Techniques, and Common Knowledge）由MITRE公司维护，是网络安全领域最权威的攻击行为知识库。',
'',
'**三个核心概念——必须分清：**',
'',
'| 概念 | 英文 | 含义 | 打个比方 |',
'|:---|:---|:---|:---|',
'| 战术（Tactics） | Tactical Goals | 攻击者的"目标"——他想干什么 | "我要进入大楼"（初始访问） |',
'| 技术（Techniques） | Techniques | 实现战术的"具体方法" | "从窗户翻进去"或"冒充员工刷卡" |',
'| 子技术（Sub-techniques） | Sub-techniques | 技术的"变种和细化" | "打碎玻璃翻窗户"vs"撬锁翻窗户" |',
'',
'**ATT&CK矩阵的11个战术（Tactics）：**',
'',
'| # | 战术名称 | 编号 | 含义（大白话） |',
'|:---|:---|:---|:---|',
'| 1 | 初始访问（Initial Access） | TA0001 | 怎么进门的——钓鱼邮件、漏洞利用、弱口令 |',
'| 2 | 执行（Execution） | TA0002 | 怎么让恶意代码跑起来——PowerShell、脚本、WMI |',
'| 3 | 持久化（Persistence） | TA0003 | 怎么保证下次还能进来——注册表、计划任务、服务 |',
'| 4 | 提权（Privilege Escalation） | TA0004 | 怎么从普通用户变成管理员——漏洞提权、令牌窃取 |',
'| 5 | 防御绕过（Defense Evasion） | TA0005 | 怎么不被发现——混淆代码、关闭杀软、清除日志 |',
'| 6 | 凭据访问（Credential Access） | TA0006 | 怎么偷密码——内存dump、hash传递、键盘记录 |',
'| 7 | 发现（Discovery） | TA0007 | 怎么了解内网环境——扫描网络、查看域信息、枚举信息 |',
'| 8 | 横向移动（Lateral Movement） | TA0008 | 怎么从一台机器跳到另一台——RDP、SSH、PsExec |',
'| 9 | 收集（Collection） | TA0009 | 怎么搜刮敏感数据——文件搜索、屏幕截图、邮件搜索 |',
'| 10 | C2通信（Command and Control） | TA0011 | 怎么保持远程控制——HTTP/HTTPS/DNS隧道 |',
'| 11 | 数据渗出（Exfiltration） | TA0010 | 怎么把数据偷偷传出去——加密传输、分段传输 |',
'',
'### 二、Kill Chain——攻击的7个环节，每个都是你的拦截机会',
'',
'杀伤链（Cyber Kill Chain）由Lockheed Martin提出，把一次完整攻击分解为7个步骤。',
'',
'| 步骤 | 名称 | 攻击者在做什么 | 蓝队检测/防御手段 | 如果这步拦住了... |',
'|:---|:---|:---|:---|:---|',
'| 1 | 侦察(Recon) | 收集目标信息：IP/域名/员工邮箱/技术栈 | 监控扫描行为、隐藏服务器信息 | 攻击者连目标长啥样都不知道 |',
'| 2 | 武器化(Weaponize) | 制作攻击工具：带后门的文档、恶意payload | 威胁情报提前获知恶意Hash | 恶意文件到不了用户手里 |',
'| 3 | 投递(Delivery) | 把武器送进去：钓鱼邮件、上传webshell | 邮件过滤、WAF拦截、安全意识培训 | 武器送到了但没人打开 |',
'| 4 | 利用(Exploit) | 触发漏洞执行代码 | IPS/EDR/WAF拦截exploit行为 | 漏洞被触发但代码没执行 |',
'| 5 | 安装(Install) | 安装后门、持久化程序 | EDR拦截恶意软件安装 | 后门装不上 |',
'| 6 | C2通信(C2) | 建立远程控制通道 | 网络流量分析、DNS监控 | 后门装了但连不上控制端 |',
'| 7 | 行动(Act) | 达成目标：窃取数据、破坏系统 | DLP数据防泄露、异常流量检测 | 折腾半天什么都没偷到 |',
'',
'> **核心认知**：攻击者必须完成全部7步才算成功。你只需要在任何一步拦住他——攻击链就断了。而且攻击越往后（越靠近第7步），蓝队就越被动。所以**最佳防御是把攻击扼杀在早期阶段**（第1-3步）。',
'',
'### 三、ATT&CK + Kill Chain 结合使用——蓝队的"攻防地图"',
'',
'把Kill Chain的每个阶段映射到ATT&CK的战术：',
'',
'| Kill Chain阶段 | 对应ATT&CK战术 | 关键检测技术 | 蓝队典型操作 |',
'|:---|:---|:---|:---|',
'| 侦察 | TA0043(侦察) | 流量监控、扫描检测 | 防火墙拒绝扫描IP、隐藏Server头 |',
'| 投递 | TA0001(初始访问) | 钓鱼检测、Web攻击检测 | WAF/IDS/邮件网关告警 |',
'| 利用 | TA0002(执行) | exploit检测、异常进程监控 | EDR/IPS检测并阻断 |',
'| 安装 | TA0003+TA0005 | 注册表监控、启动项监控 | HIPS拦截、EDR告警 |',
'| C2 | TA0011(C2通信) | DNS监控、异常外连检测 | 防火墙出站策略、DNS sinkhole |',
'| 行动 | TA0009+TA0010 | DLP、大流量异常检测 | DLP阻断、流量清洗 |',
'',
'> **背下来**：这7x11的对应关系就是你防御能力评估的检查清单。护网前逐个检查——每个Kill Chain阶段我们有没有对应的检测/防御手段？',
'',
'### 四、蓝队如何用ATT&CK做防御能力评估',
'',
'这是蓝队最核心的实战技能之一。',
'',
'**Step 1：列出你的防御资产清单**',
'```',
'你有哪些安全设备：防火墙/WAF/IDS/EDR/SIEM...',
'每个设备能检测/防御什么类型的攻击？各覆盖哪些ATT&CK战术？',
'```',
'',
'**Step 2：逐战术对照覆盖度**',
'ATT&CK有11个战术，对每个战术问：',
'- 我们有没有覆盖这个战术的检测手段？',
'- 覆盖得够不够？（比如"横向移动"只有IDS一条规则 vs 三层检测）',
'',
'**Step 3：打分和优先级排序**',
'',
'| 战术 | 覆盖度 | 评分(1-5) | 优先级 |',
'|:---|:---|:---|:---|',
'| 初始访问 | WAF+防火墙+IPS三层 | 4 | 中 |',
'| 持久化 | 只有EDR | 3 | 高（单点覆盖） |',
'| 横向移动 | 无专门检测 | 1 | 🔴 最高（盲区！） |',
'| C2通信 | 只有出站防火墙 | 2 | 🔴 最高 |',
'',
'**Step 4：制定改进计划**：针对评分最低的战术优先补充防御手段。',
'',
'> **面试加分点**：面试官问"你做过防御能力评估吗"，你回答"我用ATT&CK框架对11个战术逐项评估覆盖率，发现横向移动和C2通信是覆盖盲区，针对性补充了检测规则..."——体系化防御思维立刻体现。',
'',
'### 五、ATT&CK实战导航——你该怎么用这个框架',
'',
'**学习阶段（现在）**：',
'1. 打开 https://attack.mitre.org/ → 先只看"Enterprise Matrix"',
'2. 随便点一个技术（如 T1059 Command and Scripting Interpreter）→ 看描述、检测方法、缓解措施',
'3. 每天学新攻击技术时，去ATT&CK找到它的编号——养成"ATT&CK Mapping"肌肉记忆',
'',
'**中级阶段**：',
'1. 用ATT&CK Navigator画热力图——红色=覆盖不足，绿色=覆盖良好',
'2. 把你的检测规则和ATT&CK技术一一对应',
'3. 做Gap Analysis：哪些ATT&CK技术我们完全没覆盖？',
'',
'**高级阶段**：',
'1. 基于ATT&CK构建威胁模型：某APT组织常用的技术组合→针对性强化对应检测',
'2. 自动化ATT&CK覆盖度评估',
'3. 输出"ATT&CK防御成熟度报告"',
'',
'### 六、10个最高频的ATT&CK技术——今天先记住这些',
'',
'| T编号 | 技术名称 | 大白话 | 为什么重要 |',
'|:---|:---|:---|:---|',
'| T1059 | Command & Scripting Interpreter | 用PowerShell/bash执行命令 | 攻击者最常用执行方式 |',
'| T1078 | Valid Accounts | 用偷来的合法账户登录 | 最难检测——和正常登录没区别 |',
'| T1566 | Phishing | 钓鱼邮件 | 90%以上APT攻击的突破点 |',
'| T1190 | Exploit Public-Facing App | 利用公网应用漏洞 | Web应用是最大攻击面 |',
'| T1505.003 | Web Shell | Webshell后门 | Web攻击后的常见持久化手段 |',
'| T1110 | Brute Force | 暴力破解 | 最常见且最易检测的攻击 |',
'| T1041 | Exfiltrate Over C2 Channel | 通过C2通道偷数据 | 数据泄露的最后一步 |',
'| T1021.001 | Remote Desktop Protocol | RDP横向移动 | 内网横移最常用方法 |',
'| T1003.001 | LSASS Memory | 从内存偷密码Hash | 拿到密码=拿到整个域的钥匙 |',
'| T1486 | Data Encrypted for Impact | 勒索软件加密数据 | 近年增长最快的攻击类型 |',
'',
'> **记忆法**：不必死记T编号。记住"ATT&CK有11列战术，每列下面一堆T编号技术"。分析攻击时把看到的攻击行为对应到T编号——这就是ATT&CK Mapping。',
'',
'---',
'',
'## 🔧 实操任务',
'',
'1. 打开 https://attack.mitre.org/ → 浏览Enterprise Matrix → 找到T1059技术 → 看它的检测方法（Detection）和缓解措施（Mitigations）',
'2. 打开 https://mitre-attack.github.io/attack-navigator/ → 下载ATT&CK Navigator → 尝试创建一张"你自己"的防御热力图（哪怕只有5个格子，熟悉操作）',
'3. 用Kill Chain的7个阶段分析一次真实攻击事件（如Log4j漏洞利用）：每个阶段发生了什么？可以在哪里拦截？',
'4. 搜索"ATT&CK 蓝队 检测"找一篇中文文章，加深理解',
'5. 将Day 19-20学到的攻击类型（端口扫描/SQL注入/XSS等）对应到ATT&CK的技术编号',
'',
'---',
'',
'## ✅ 验收标准',
'',
'- [ ] 能解释ATT&CK的战术(Tactics)和技术(Techniques)的区别',
'- [ ] 能说出Kill Chain的7个阶段及每阶段的蓝队检测/防御手段',
'- [ ] 能找到ATT&CK矩阵中至少5个战术编号及其对应的技术',
'- [ ] 能用自己的话说清楚"ATT&CK Mapping"是什么、为什么要做',
'- [ ] 理解"攻击越早拦截越好"的纵深防御思想',
'',
'---',
'',
'## 📝 今日小结',
'',
'今天学会了蓝队最重要的知识框架——ATT&CK和Kill Chain。ATT&CK = 所有攻击技术的百科全书（11个战术、数百个技术），Kill Chain = 把这些技术串成攻击链（7个阶段）。把两者结合起来，你就有了评估防御能力的"参照系"——知道攻击者怎么来，才知道防御应该设在哪。关键术语回顾：战术/技术/子技术、7阶段杀伤链、ATT&CK Mapping。这是后续所有攻击识别和防御评估的基础框架。',
'',
'---',
'',
'## 📚 延伸阅读',
'',
'- ATT&CK官网 → https://attack.mitre.org/',
'- ATT&CK Navigator → https://mitre-attack.github.io/attack-navigator/',
'- Lockheed Martin: The Cyber Kill Chain 原始论文',
'- 搜索"ATT&CK 中文入门"找中文解读加深理解',
'- 搜索"ATT&CK for CTI"了解如何用于威胁情报分析',
)

# ===== RUN =====
if __name__ == '__main__':
    lines = write_md(29, d29)
    print(f'Day 29: {lines} lines')
