#!/usr/bin/env python3
"""Round 3 supplement: add rich deep-dive content to Days 3-28 still below 500 lines."""
import os

OUT = '.'

def append_to(day, lines_list):
    fname = os.path.join(OUT, f'day-{day}.md')
    if not os.path.exists(fname):
        print(f'  Day {day}: MISSING')
        return 0
    with open(fname, 'r', encoding='utf-8') as f:
        old = f.read()
    old_count = old.count('\n')
    extra = '\n'.join(lines_list)
    new_content = old.rstrip('\n') + '\n\n' + extra + '\n'
    with open(fname, 'w', encoding='utf-8') as f:
        f.write(new_content)
    nc = new_content.count('\n')
    print(f'  Day {day:3d}: {old_count:4d} → {nc:4d} (+{nc-old_count})')
    return nc

# ======= GENERIC DEEP-DIVE BLOCKS =======

def deep_dive_block(title, sections):
    """Build a '深度专题' block with multiple subsections."""
    lines = ['', '---', '', f'## 🔬 深度专题：{title}', '']
    for sub_title, sub_body in sections:
        lines.append(f'### {sub_title}')
        lines.append('')
        if isinstance(sub_body, list):
            lines.extend(sub_body)
        else:
            lines.append(sub_body)
        lines.append('')
    return lines

def tool_tips_block(title, tips):
    lines = ['', '---', '', f'## 🛠️ 工具实操技巧：{title}', '']
    for t in tips:
        lines.append(t)
        lines.append('')
    return lines

def knowledge_map_block(connections):
    """Build a knowledge connection map."""
    lines = ['', '---', '', '## 🗺️ 知识串联图谱', '']
    lines.append('将今天的知识点与之前学过的内容串联起来，形成知识网络：')
    lines.append('')
    for c in connections:
        lines.append(c)
    lines.append('')
    return lines

# ======= DAY-SPECIFIC DEEP DIVES =======

# Day 3 — currently 493, need ~20 more
D3_DEEP = deep_dive_block('HTTP安全头与蓝队检测', [
    ('安全响应头详解', [
        '蓝队在安全检查中必须关注以下HTTP安全响应头的配置情况：',
        '',
        '**1. Content-Security-Policy (CSP)**',
        '- 作用：限制浏览器可以加载哪些来源的资源（脚本/样式/图片/字体）',
        '- 蓝队检查：是否配置了CSP？是否过于宽松（如default-src *）？',
        '- 检测命令：`curl -I https://target.com | grep Content-Security-Policy`',
        '- 典型攻击场景：XSS攻击成功后需要加载恶意脚本→CSP可以阻止外域脚本加载',
        '',
        '**2. X-Frame-Options**',
        '- 作用：防止点击劫持（Clickjacking）——攻击者将你的网站嵌入iframe中',
        '- 推荐值：`DENY`（禁止任何iframe嵌入）或`SAMEORIGIN`（允许同域嵌入）',
        '- 检测命令：`curl -I https://target.com | grep X-Frame-Options`',
        '',
        '**3. X-Content-Type-Options**',
        '- 作用：防止浏览器MIME类型嗅探——攻击者可能上传伪装成图片的恶意脚本',
        '- 推荐值：`nosniff`',
        '- 蓝队核查：如果缺失此头，文件上传漏洞的风险成倍增加',
        '',
        '**4. Strict-Transport-Security (HSTS)**',
        '- 作用：强制浏览器使用HTTPS访问，防止SSL剥离攻击',
        '- 推荐值：`max-age=31536000; includeSubDomains; preload`',
        '- 蓝队核查：对外网站未配置HSTS=高风险',
        '',
        '**5. Referrer-Policy**',
        '- 作用：控制Referer头的发送策略——避免信息泄露',
        '- 蓝队关注：如果Referer泄露了敏感URL参数（如token/session ID），攻击者可以通过Referer窃取',
    ]),
    ('HTTP请求走私攻击简介', [
        'HTTP请求走私（Request Smuggling）是一种利用前端代理/负载均衡器与后端服务器对HTTP请求边界理解不一致的攻击手法。攻击者构造特殊的HTTP请求，使前端和后端对请求的解析不同，从而将一个请求\"走私\"到下一个用户的请求中。',
        '',
        '**蓝队检测思路**：',
        '1. 检查Content-Length和Transfer-Encoding头是否同时出现且值不一致',
        '2. 监控HTTP 400错误突增（请求走私通常导致后端解析失败）',
        '3. 关注同一连接上请求时序异常',
        '4. 确保前端代理和后端服务器使用相同的HTTP解析器或关闭请求复用',
        '',
        '> 虽然HTTP请求走私是高级攻击手法，但蓝队了解其原理有助于理解\"为什么HTTP协议的安全不是理所当然的\"。',
    ]),
])

# Day 4 — currently 477, need ~30 more
D4_DEEP = deep_dive_block('Linux权限模型与安全审计', [
    ('SUID/SGID/GUID深度解析——攻击者最爱的提权点', [
        'Linux的SUID（Set User ID）是蓝队安全排查中必须重点关注的权限位。',
        '',
        '**SUID的工作原理**：当一个可执行文件设置了SUID位，执行该文件时，进程将以文件属主（通常是root）的身份运行，而非执行者的身份。',
        '',
        '**攻击者如何利用SUID提权**：',
        '```bash',
        '# 查找所有SUID文件',
        'find / -perm -4000 -type f 2>/dev/null',
        '',
        '# 常见的不安全SUID程序（GTFOBins中有利用方法）',
        '# /usr/bin/find → find . -exec /bin/sh \\; → 提权为root',
        '# /usr/bin/vim → vim -c \":!sh\" → 提权为root',
        '# /usr/bin/bash → bash -p → 以root权限运行bash',
        "# /usr/bin/python → python -c \"import os; os.system('/bin/sh')\"",
        '```',
        '',
        '**蓝队安全基线检查**：',
        '1. 定期审计所有SUID文件（对比基线，发现新增的SUID文件=后门）',
        '2. 对于业务不需要的SUID程序，移除SUID位：`chmod u-s /path/to/file`',
        '3. 对于必需的SUID程序，限制执行权限（仅特定组可执行）',
        '4. 使用auditd监控SUID文件的创建和执行',
        '',
        '**应急排查命令**：',
        '```bash',
        '# 列出今天新增的SUID文件（对比昨天的快照）',
        'diff <(find / -perm -4000 -type f 2>/dev/null | sort) <(cat /var/backup/suid_baseline.txt)',
        '```',
    ]),
    ('Linux的5种特殊权限位速查', [
        '| 权限位 | 数值 | 含义 | 蓝队关注点 |',
        '| --- | --- | --- | --- |',
        '| SUID | 4000 | 以文件属主身份执行 | 攻击者提权的主要利用点 |',
        '| SGID | 2000 | 以文件属组身份执行 | 目录SGID可使新建文件继承目录组 |',
        '| Sticky Bit | 1000 | 仅文件属主可删除（如/tmp） | 防止普通用户删除他人文件 |',
        '| Capabilities | - | 细粒度权限（超越root） | 可能被滥用来绕过权限限制 |',
        '| ACL | - | 访问控制列表 | 比传统rwx更灵活，但也更复杂 |',
    ]),
])

# Day 5 — currently 424, need ~80 more
D5_DEEP = deep_dive_block('Linux三剑客进阶——蓝队日志分析实战', [
    ('grep高级用法：蓝队日志分析必杀技', [
        '基础grep只是入门，以下进阶用法能让你在日志分析中快人一步：',
        '',
        '**1. 正则表达式组合检测**',
        '```bash',
        '# 同时检测多种攻击（SQL注入+XSS+路径遍历）',
        'grep -iP \"(union.*select|<script>|\\.\\./\\.\\./|sleep\\(|cmd=|exec\\(|wget |curl )\" access.log',
        '```',
        '',
        '**2. 上下文输出（看攻击前后的请求）**',
        '```bash',
        '# 显示匹配行的前后3行——还原攻击链上下文',
        'grep -iP -B3 -A3 \"union.*select\" access.log',
        '```',
        '',
        '**3. 反向匹配（排除噪声）**',
        '```bash',
        '# 排除CDN和已知正常IP的访问',
        'grep -v -E \"(1.2.3.4|cdn\\.example\\.com|googlebot)\" access.log | grep -i \"union\"',
        '```',
        '',
        '**4. 计数统计（攻击频率分析）**',
        '```bash',
        '# 统计每种攻击的发生频率',
        'grep -c \"union.*select\" access.log  # SQL注入次数',
        'grep -c \"<script>\" access.log        # XSS次数',
        'grep -c \"\\\\.\\\\./\\\\.\\\\./\" access.log  # 路径遍历次数',
        '```',
    ]),
    ('awk进阶：从简单提取到统计分析', [
        '**1. 按时间段统计攻击**',
        '```bash',
        '# 统计每小时的SQL注入攻击次数',
        "grep -i \"union\" access.log | awk -F':' '{print $2\":\"$3}' | cut -d':' -f1,2 | sort | uniq -c | sort -rn",
        '```',
        '',
        '**2. 计算攻击者排名和贡献度**',
        '```bash',
        '# 统计每个攻击IP的攻击次数和占比',
        "awk '{ips[$1]++} END {for(i in ips) printf \"%-20s %5d %.1f%%\\n\", i, ips[i], ips[i]*100/NR}' access.log | sort -k2 -rn | head -20",
        '```',
        '',
        '**3. 提取并统计User-Agent（发现自动化工具）**',
        '```bash',
        '# 统计UA分布，发现异常值',
        "awk -F'\"' '{print $6}' access.log | sort | uniq -c | sort -rn | head -20",
        '# 如果看到sqlmap/XSS扫描器/Python脚本的UA → 确认自动化攻击',
        '```',
        '',
        '**4. 响应体大小分析（发现拖库行为）**',
        '```bash',
        '# 统计响应体大小的TOP10（异常大的可能是拖库）',
        "awk '{print $10}' access.log | sort -rn | head -10",
        '# 结合状态码200 + 异常大的响应体 = 拖库特征',
        '```',
    ]),
    ('sed在蓝队中的5个实用场景', [
        '1. **日志脱敏**：`sed \"s/[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}/x.x.x.x/g\" access.log > sanitized.log`',
        '2. **时间范围提取**：`sed -n \"/08:00/,/12:00/p\" access.log > morning.log`',
        '3. **特定请求方法筛选**：`sed -n \"/POST/p\" access.log > post_requests.log`',
        '4. **移除无关字段**：`sed \"s/ - - \\[.*\\] //\" access.log`  # 去掉时间戳和用户字段，精简日志',
        '5. **格式化输出**：`sed \"s/\\\"GET /GET: /; s/ HTTP.*//\" access.log | awk \"{print \\$1, \\$4}\" | head`  # 提取IP和请求路径',
    ]),
    ('组合技巧：三剑客联动分析', [
        '最强大的分析不是单独使用grep/awk/sed，而是将它们串联起来：',
        '',
        '```bash',
        '# 实战案例：找出SQL注入攻击者TOP10并提取它们的完整攻击链',
        "grep -i \"union.*select\" access.log | awk '{print $1}' | sort | uniq -c | sort -rn | head -10 | while read count ip; do",
        '  echo \"=== IP: $ip (攻击$count次) ===\"',
        '  grep \"$ip\" access.log | head -5  # 显示该IP的前5条请求',
        '  echo ""',
        'done',
        '```',
        '',
        '**分析链路**：grep筛选攻击 → awk提取IP → sort+uniq统计 → while循环逐个分析 → 输出攻击者行为画像。',
        '',
        '这就是\"三剑客\"的真正威力——不是各自为战，而是无缝协作。',
    ]),
])

# Day 8 — currently 426, need ~80 more
D8_DEEP = deep_dive_block('Wireshark进阶：协议分析与攻击检测', [
    ('TCP流追踪进阶——还原完整攻击会话', [
        '基础TCP流追踪只能看单个连接，进阶用法可以还原跨连接的攻击链：',
        '',
        '**1. 追踪攻击者的完整行为时间线**',
        '```bash',
        '# 提取攻击IP的所有TCP会话',
        'tshark -r attack.pcap -Y \"ip.src==192.168.1.100 || ip.dst==192.168.1.100\" -T fields \\',
        '  -e frame.time -e ip.src -e ip.dst -e tcp.srcport -e tcp.dstport -e tcp.flags.syn -e tcp.flags.fin',
        '```',
        '',
        '**2. 检测异常TCP行为**',
        '- SYN包数量/FIN包数量 > 3 = 可能存在SYN Flood攻击',
        '- 大量RST包 = 端口扫描或连接中断攻击',
        '- 零窗口（Zero Window）持续 = 接收端资源耗尽或DoS',
        '- TCP窗口大小异常波动 = 可能的中间人攻击',
        '',
        '**3. Wireshark专家信息（Expert Info）的使用**',
        '- Analyze → Expert Info → 查看Wireshark自动识别出的协议异常',
        '- Warning级别的\"TCP Retransmission\"、\"TCP Dup ACK\"、\"TCP Out-Of-Order\"需要关注',
        '- 如果集中在某个时间段突然出现大量Warning = 可能有攻击',
    ]),
    ('DNS协议分析——发现隐蔽隧道', [
        'DNS是蓝队最常被忽视的协议之一。攻击者经常利用DNS做隐蔽通信（DNS隧道）：',
        '',
        '**DNS隧道的流量特征**：',
        '- 大量TXT/MX/CNAME类型的查询（正常DNS查询以A/AAAA为主）',
        '- 请求的域名异常长（如`dGhpcyBpcyBhIHRlc3QK.malicious.com`——前面是一段Base64编码）',
        '- 短时间内大量DNS查询同一域名的不同子域名（数据分片传输）',
        '- DNS响应包异常大（正常的DNS响应通常<512字节）',
        '',
        '**Wireshark检测命令**：',
        '```bash',
        '# 统计DNS查询类型分布',
        'tshark -r capture.pcap -Y \"dns.flags.response == 0\" -T fields -e dns.qry.type | sort | uniq -c',
        '',
        '# 查找异常长的DNS查询域名',
        'tshark -r capture.pcap -Y \"dns\" -T fields -e dns.qry.name | awk \"length>50\"',
        '',
        '# 查找DNS响应大于512字节的',
        'tshark -r capture.pcap -Y \"dns.flags.response == 1 && dns.length > 512\"',
        '```',
    ]),
])

# Day 9 — currently 426, need ~80 more
D9_DEEP = deep_dive_block('Web日志分析进阶——从单条日志到攻击行为画像', [
    ('构建攻击者行为画像', [
        '蓝队不只是\"看到攻击\"，更要\"理解攻击者\"。通过日志分析构建攻击者行为画像：',
        '',
        '**攻击者画像维度**：',
        '1. **技术水平**：手工构造payload（高）vs 使用自动化工具默认payload（低）→ User-Agent和payload复杂度判断',
        '2. **攻击目标**：是广撒网式扫描还是针对特定业务接口？→ 通过请求路径的集中度判断',
        '3. **攻击阶段**：探测阶段（大量404）→漏洞验证（少量200/500）→漏洞利用（出现shell上传）→后渗透（异常文件访问）',
        '4. **持久性**：攻击者是单次尝试还是持续攻击？→ 分析攻击时间跨度和频率',
        '5. **使用的工具**：通过User-Agent、payload结构、请求频率推断（Nmap/sqlmap/BurpSuite/自写脚本）',
        '',
        '**画像输出模板**：',
        '```',
        '【攻击者画像报告】',
        '源IP: xxx.xxx.xxx.xxx | 地理位置: 境外/境内',
        '技术等级: 高级/中级/初级',
        '攻击类型: SQL注入 + 目录扫描',
        '攻击阶段: 漏洞利用阶段（已成功获取数据库名和表名）',
        '使用工具: sqlmap（根据payload结构、时间盲注特征判断）',
        '首次发现: 2026-06-18 10:05 | 最近活动: 2026-06-18 14:30',
        '攻击频次: 共发出230+次恶意请求 | 峰值: 10:15-10:30（40次/分钟）',
        '当前状态: 已被WAF封禁 | 建议: 排查漏铜并修复',
        '```',
    ]),
    ('日志基线建立方法', [
        '没有基线的日志分析就像没有参考系的导航。以下是建立日志基线的实操方法：',
        '',
        '**第一步：收集一周的正常日志（非护网期、无已知攻击时段）**',
        '```bash',
        '# 确保日志覆盖所有业务时段（工作日/周末/白天/夜间）',
        'ls -lh /var/log/nginx/access.log*',
        '```',
        '',
        '**第二步：统计基线指标**',
        '```bash',
        '# 每小时平均请求量',
        "awk -F':' '{print $2}' access.log | cut -c1-2 | sort | uniq -c",
        '',
        '# 正常状态码分布',
        "awk '{print $9}' access.log | sort | uniq -c | sort -rn",
        '',
        '# 正常请求路径TOP20',
        "awk '{print $7}' access.log | sort | uniq -c | sort -rn | head -20",
        '',
        '# 正常源IP TOP20',
        "awk '{print $1}' access.log | sort | uniq -c | sort -rn | head -20",
        '```',
        '',
        '**第三步：设定告警阈值**',
        '```',
        '# 基于基线设定偏离阈值（以标准差或百分比）',
        '请求量 > 基线的2倍 → 告警',
        '404比例 > 基线的3倍 → 扫描告警',
        '500比例 > 基线的5倍 → 攻击告警',
        '出现基线中不存在的IP且高频访问 → 可疑',
        '```',
    ]),
])

# Day 10 — currently 425, need ~80 more
D10_DEEP = deep_dive_block('系统日志关联分析——构建攻击全景图', [
    ('多日志源关联分析实战', [
        '单一日志只能看一个角度。真正的分析需要把Web日志、系统日志、安全设备日志串联起来：',
        '',
        '**场景：还原一次完整的Web入侵**',
        '',
        '**Step 1：从WAF日志发现入口**',
        '```bash',
        'grep \"SQL Injection\" /var/log/waf/alert.log | tail -5',
        '# 输出：2026-06-18 10:05:23 SQL Injection from 45.xx.xx.xx to /api/query.php',
        '```',
        '',
        '**Step 2：到Web日志查看攻击全貌**',
        '```bash',
        'grep \"45.xx.xx.xx\" /var/log/nginx/access.log | tail -20',
        '# 发现攻击者从10:05到10:15发出了各种SQL注入payload',
        '# 10:12有一条返回200且响应体达50KB的请求 → 可能成功拖库',
        '```',
        '',
        '**Step 3：查系统日志看攻击者是否已获得服务器权限**',
        '```bash',
        'grep \"45.xx.xx.xx\" /var/log/secure',
        '# 发现10:18有一条：Accepted password for www-data from 45.xx.xx.xx',
        '# → 攻击者已经通过SQL注入写入webshell并获得了服务器权限！',
        '```',
        '',
        '**Step 4：查进程日志看攻击者做了什么**',
        '```bash',
        '# 检查bash_history（攻击者可能已删除，改用auditd）',
        'ausearch -ts 06/18/2026 \"10:15:00\" -te 06/18/2026 \"10:30:00\" | grep \"45.xx.xx.xx\"',
        '# 发现攻击者下载了内网扫描工具、尝试连接数据库',
        '```',
        '',
        '**结论**：这就是日志关联分析的威力——WAF日志→Web日志→系统日志→进程日志，逐层深入，最终还原完整攻击链。',
    ]),
    ('自动化日志关联脚本', [
        '手动逐个查日志太慢，蓝队需要自动化关联脚本：',
        '',
        '```bash',
        '#!/bin/bash',
        '# auto_trace.sh - 根据IP自动追溯攻击链',
        'TARGET_IP=$1',
        'echo \"=== 攻击链追溯: $TARGET_IP ===\"',
        'echo \"\"',
        'echo \"--- WAF告警 ---\"',
        'grep \"$TARGET_IP\" /var/log/waf/alert.log 2>/dev/null | tail -10',
        'echo \"\"',
        'echo \"--- Web访问日志 ---\"',
        'grep \"$TARGET_IP\" /var/log/nginx/access.log 2>/dev/null | tail -20',
        'echo \"\"',
        'echo \"--- SSH登录尝试 ---\"',
        'grep \"$TARGET_IP\" /var/log/secure 2>/dev/null | tail -10',
        'echo \"\"',
        'echo \"--- 防火墙日志 ---\"',
        'grep \"$TARGET_IP\" /var/log/firewall.log 2>/dev/null | tail -10',
        'echo \"\"',
        'echo \"--- 进程审计（最近1小时）---\"',
        'ausearch -k process_tracking --start recent 2>/dev/null | grep -A2 \"$TARGET_IP\" | head -30',
        '```',
        '',
        '将此类脚本保存为工具集，护网期间通过一条命令快速追溯任意攻击IP的完整行为。',
    ]),
])

# Day 15 (firewall/WAF) — currently 358, need ~150 more
D15_DEEP = deep_dive_block('防火墙与WAF深度对比——蓝队防护体系基石', [
    ('防火墙规则优化实战', [
        '**1. 最小权限原则的iptables实现**',
        '```bash',
        '#!/bin/bash',
        '# 默认拒绝所有入站流量',
        'iptables -P INPUT DROP',
        '# 允许已建立的连接',
        'iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT',
        '# 允许SSH（仅限内网）',
        'iptables -A INPUT -p tcp -s 192.168.0.0/16 --dport 22 -j ACCEPT',
        '# 允许HTTP/HTTPS',
        'iptables -A INPUT -p tcp --dport 80 -j ACCEPT',
        'iptables -A INPUT -p tcp --dport 443 -j ACCEPT',
        '# 记录被拒绝的连接',
        'iptables -A INPUT -j LOG --log-prefix \"IPTABLES-DROP: \" --log-level 4',
        '```',
        '',
        '**2. 防暴力破解规则**',
        '```bash',
        '# SSH防爆破（60秒内超过3次新连接则封禁）',
        'iptables -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --set --name SSH',
        'iptables -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --update --seconds 60 --hitcount 3 --name SSH -j DROP',
        '```',
        '',
        '**3. WAF日志分析——发现规则优化点**',
        '```bash',
        '# 统计WAF拦截最多的规则（TOP10）',
        "grep \"blocked\" waf.log | awk -F'rule_id=' '{print $2}' | awk '{print $1}' | sort | uniq -c | sort -rn | head -10",
        '',
        '# 统计WAF误报（返回403但实为正常业务的请求）',
        "grep \"403\" nginx_access.log | grep -v \"waf\"",
        '```',
    ]),
    ('下一代防火墙（NGFW）的核心能力', [
        '现代护网环境中，传统防火墙已升级为NGFW（下一代防火墙），蓝队需要了解其核心差异：',
        '',
        '| 能力 | 传统防火墙 | NGFW |',
        '| --- | --- | --- |',
        '| 工作层 | L3/L4 | L3-L7 |',
        '| 规则粒度 | IP+端口 | IP+端口+应用+用户+内容 |',
        '| 应用识别 | 仅端口 | 深度包检测（DPI），识别端口上的实际应用 |',
        '| 用户识别 | 无 | 集成AD/LDAP，用户级别策略 |',
        '| IPS集成 | 无（需单独部署） | 内置IPS引擎 |',
        '| 威胁情报 | 无 | 集成实时威胁情报 |',
        '| SSL检测 | 无法 | SSL解密后检测 |',
        '',
        '**蓝队NGFW实操要点**：',
        '- 启用应用识别——不要仅依赖端口做策略',
        '- 开启SSL解密（对核心业务段的流量）',
        '- 配置用户级别策略——\"研发部门不能访问外部网盘\"',
        '- 联动威胁情报——自动封禁已知恶意IP',
    ]),
])

# Day 18 (告警研判) — currently 341, need ~160 more
D18_DEEP = deep_dive_block('告警研判高级技巧——从\"看一条告警\"到\"看攻击全貌\"', [
    ('告警关联分析——\"串珠成链\"', [
        '单条告警看不出全貌，关联分析才能还原攻击链：',
        '',
        '**场景1：扫描+注入+上传 = 完整攻击链**',
        '```',
        '10:00 - IDS: 端口扫描 from IP-X（目录扫描探测）',
        '10:05 - WAF: SQL注入尝试 from IP-X（利用找到的接口注入）',
        '10:08 - WAF: SQL注入成功（响应异常大）',
        '10:10 - WAF: 文件上传 .php from IP-X（写入webshell）',
        '10:11 - Proxy: 访问 /uploads/shell.php（验证webshell）',
        '10:15 - EDR: 异常进程启动（webshell执行系统命令）',
        '```',
        '→ 关联结论：完成了一次完整的SQL注入→Webshell上传→命令执行的攻击链！',
        '',
        '**场景2：看似无关的告警其实是一个攻击者的多线作战**',
        '```',
        '09:00 - WAF1: SQL注入 to 业务A',
        '09:02 - WAF2: XSS to 业务B',
        '09:05 - NIDS: SSH爆破 to 服务器C',
        '→ 源IP都是同一个 → 攻击者在同时对多个目标发起不同类型攻击',
        '```',
    ]),
    ('告警研判决策树（Decision Tree）', [
        '将研判经验体系化，建立决策树可以加速新人培训：',
        '',
        '```',
        '收到告警 →',
        '  ├── 告警源IP是CDN/代理IP？ → YES → 大概率误报，记录观察',
        '  │   └── NO → 继续 →',
        '  ├── 告警目标是核心业务资产？ → YES → 提升优先级为P1+',
        '  │   └── NO → 继续 →',
        '  ├── 攻击payload被WAF成功拦截？ → YES → P3级别，记录IP加入监控',
        '  │   └── NO → 继续 →',
        '  ├── 同一IP在5分钟内触发了>10条告警？ → YES → P2级别，疑似持续性攻击',
        '  │   └── NO → 继续 →',
        '  ├── 告警包含webshell/后门特征？ → YES → P0级别，立即隔离',
        '  │   └── NO → 继续 →',
        '  ├── 响应状态码200且响应体异常大？ → YES → P0级别，可能数据泄露中',
        '  │   └── NO → P3级别，常规记录',
        '```',
    ]),
])

# Day 20 (攻击识别-入侵类) — currently 316, need ~190 more
D20_DEEP = deep_dive_block('高级入侵检测——日志中的\"微特征\"', [
    ('SSRF攻击——容易被忽视的内网探测', [
        'SSRF（服务端请求伪造）让攻击者以服务器为跳板访问内网资源，蓝队检测难度较大：',
        '',
        '**检测特征**：',
        '1. URL参数中出现内网地址（127.0.0.1/10.x.x.x/172.16.x.x/192.168.x.x）',
        '2. 参数中出现非HTTP协议的URL（file:///、gopher://、dict://）',
        '3. 请求参数指向云元数据服务（169.254.169.254——AWS/阿里云等元数据地址）',
        '4. 短时间内同一接口被用来请求多个不同的内网地址→端口扫描式探测',
        '',
        '**检测命令**：',
        '```bash',
        '# 检测URL参数中的内网IP',
        "grep -iE \"(127\\.0\\.0\\.1|10\\.[0-9]+\\.[0-9]+\\.[0-9]+|172\\.(1[6-9]|2[0-9]|3[0-1])\\.|192\\.168\\.|169\\.254\\.169\\.254)\" access.log",
        '',
        '# 检测协议绕过',
        "grep -iE \"(file://|gopher://|dict://|ftp://)\" access.log",
        '```',
    ]),
    ('XXE攻击——XML中的外实体注入', [
        'XXE（XML外部实体注入）利用XML解析器的外部实体功能读取服务器文件：',
        '',
        '**检测特征**：',
        '- Content-Type为`application/xml`或`text/xml`',
        '- 请求体中包含`<!ENTITY`、`SYSTEM`等XML实体声明',
        '- 请求体中包含`file:///etc/passwd`、`file:///c:/windows/win.ini`等文件路径',
        '',
        '**检测命令**：',
        '```bash',
        '# 搜索XXE特征',
        "grep -iE \"(<!ENTITY|SYSTEM \\\"file://|SYSTEM 'file://)\" access.log",
        "grep -i \"application/xml\" access.log | grep -c \"ENTITY\"",
        '```',
        '',
        '**蓝队注意**：XXE攻击在JSON API时代有所减少，但如果你的系统还在处理XML输入（如SOAP接口、Office文档上传），就不能忽视XXE检测。',
    ]),
    ('命令注入的检测特征', [
        '不同于SQL注入，命令注入直接在服务器操作系统层面执行命令：',
        '',
        '**常见注入payload特征**：',
        '- `;` `|` `||` `&&` 后跟系统命令（id/whoami/ls/cat/wget）',
        '- `` ` ``（反引号）包裹的命令执行',
        '- `$()` 命令替换语法',
        '- 编码绕过：`%0a`（换行符）、`%0d`（回车符）绕过输入验证',
        '',
        '**检测命令**：',
        '```bash',
        "# 检测命令注入特征",
        "grep -iP \"(;\\s*(id|whoami|ls|cat|wget|curl|nc |bash|sh|python|perl)|\\|\\|\\s*(id|whoami|ls)|&&\\s*(id|whoami|ls))\" access.log",
        '',
        "# 检测换行符绕过",
        "grep -iE \"(%0a|%0d|%0d%0a)(id|whoami|cat|ls)\" access.log",
        '```',
    ]),
])

# Day 22 (emergency response) — currently 247, need ~260 more
D22_DEEP = deep_dive_block('应急响应工具箱——\"宁可用不上，不可用时没有\"', [
    ('应急响应随身U盘必备清单', [
        '每位蓝队应急人员应准备一个应急U盘，包含以下工具：',
        '',
        '**取证工具**：',
        '- Process Explorer / Process Monitor（Windows进程分析）',
        '- Autoruns（Windows启动项检查）',
        '- WinPrefetchView（Windows预读取文件分析——看到攻击者执行了什么程序）',
        '- Wireshark/TShark（流量抓包）',
        '- FTK Imager（磁盘镜像，留证用）',
        '- Volatility（内存取证）',
        '- Sleuth Kit（磁盘取证）',
        '',
        '**应急脚本**：',
        '- Windows信息收集脚本（一键导出进程/服务/启动项/网络连接/用户/计划任务）',
        '- Linux信息收集脚本（同上，适配Linux）',
        '- 网络隔离脚本（一键切断受感染机器网络但不关机）',
        '',
        '**辅助工具**：',
        '- Putty/MobaXterm（远程连接）',
        '- Notepad++（查看大日志文件）',
        '- 7-Zip（打包证据）',
        '- HashMyFiles（计算文件哈希，对比恶意样本库）',
        '',
        '**重要**：应急U盘必须**写保护**（物理只读开关），防止插入受感染机器时被恶意软件感染。另外，定期更新U盘中的工具版本。',
    ]),
    ('应急响应的\"不\"原则', [
        '应急响应中有些操作是绝对不能做的：',
        '',
        '1. **不关机**——保留内存证据（进程/网络连接/解密后的恶意代码）',
        '2. **不直接在受感染机器上操作**——通过只读U盘或网络远程取证',
        '3. **不修改系统时间**——会破坏日志取证的时间线',
        '4. **不删除任何文件**——先取证后清理，永远先收集证据',
        '5. **不信任任何运行中的进程**——rootkit可以隐藏进程/文件/网络连接，需要用可信工具（从干净系统启动）来做对比验证',
        '6. **不单独行动**——应急响应是团队工作，需要一人操作、一人记录、一人协调',
        '7. **不修复就恢复**——先找根因（怎么进来的？什么漏洞？），修复漏洞后再恢复，否则会被再次入侵',
    ]),
    ('编写应急响应报告的标准模板', [
        '一份完整的应急响应报告必须包含以下章节：',
        '',
        '```',
        '【安全事件应急响应报告】',
        '',
        '1. 事件概述',
        '   - 发现时间、发现方式（告警/用户反馈/主动巡检）',
        '   - 影响范围（系统/数据/用户）',
        '   - 严重等级（P0/P1/P2/P3）',
        '',
        '2. 事件时间线',
        '   - 攻击开始时间（入侵入口）',
        '   - 各个攻击阶段的时间点（Kill Chain）',
        '   - 发现时间',
        '   - 抑制时间',
        '   - 根除时间',
        '   - 恢复时间',
        '',
        '3. 攻击还原',
        '   - 攻击入口（漏洞类型/攻击手法）',
        '   - 攻击链路（各阶段的详细操作）',
        '   - 受损资产清单',
        '   - 数据泄露评估',
        '',
        '4. 处置措施',
        '   - 抑制措施及时间',
        '   - 根除措施（清理/修补/重装）',
        '   - 恢复措施（数据恢复/业务验证）',
        '',
        '5. 根因分析',
        '   - 为什么会被入侵？（漏洞/配置错误/人员疏忽）',
        '   - 为什么能持续这么久？（检测盲区/监控不足）',
        '',
        '6. 改进措施',
        '   - 短期措施（补丁/规则/监控加强）',
        '   - 长期措施（体系/流程/培训/工具）',
        '',
        '7. 附录',
        '   - 证据截图',
        '   - 日志摘要',
        '   - 处置工单编号',
        '```',
    ]),
])

# Day 26 (Webshell) — currently 242, need ~260 more
D26_DEEP = deep_dive_block('Webshell深度检测——从文件到内存到流量', [
    ('常见Webshell混淆手法与反混淆', [
        '攻击者通过各种手段让Webshell逃过检测，蓝队需要了解这些手法才能反制：',
        '',
        '**1. 字符串拼接混淆**',
        '```php',
        '# 明文：<?php eval($_POST[\"cmd\"]); ?>',
        '# 混淆：<?php $a=\"ev\".\"al\"; $a($_POST[\"cmd\"]); ?>',
        '# 更强混淆：<?php ${\"GLOBALS\"}[\"x\".\"x\"]=\"as\"; $xx(${\"_PO\".\"ST\"}[\"c\"]); ?>',
        '```',
        '检测思路：不仅匹配eval/system等关键字，还要检测字符串拼接模式。',
        '',
        '**2. 编码/加密混淆**',
        '```php',
        '# Base64编码：<?php eval(base64_decode(\"ZmlsZV9nZXRfY29udGVudHMoJF9HRVRbJ2YnXSk7\")); ?>',
        '# XOR加密',
        '# ROT13编码',
        '```',
        '检测思路：检测base64_decode/gzinflate/str_rot13等解码函数与危险函数的组合使用。',
        '',
        '**3. 图片马**',
        '攻击者将Webshell代码隐藏在图片文件的EXIF信息中，后端通过include方式执行。',
        '检测思路：对所有上传的\"图片\"做文件格式验证+内容扫描。',
        '',
        '**4. .htaccess配合绕过**',
        '```',
        '# 将.jpg文件当作PHP执行',
        'AddType application/x-httpd-php .jpg',
        '```',
        '检测思路：检查Web目录中的.htaccess是否有异常配置。',
    ]),
    ('Webshell流量特征——不管怎么变形，通信模式是变不了的', [
        '即使Webshell代码做了深度混淆，它的通信模式仍然有规律可循：',
        '',
        '**特征1：心跳包**',
        '- Webshell客户端（如蚁剑/冰蝎/哥斯拉）定期发送小请求确认后门存活',
        '- 特征：对同一个PHP文件的POST请求，间隔固定（如每60秒一次），请求体极短',
        '',
        '**特征2：加密通信**',
        '- 冰蝎/哥斯拉等现代Webshell使用AES加密通信',
        '- 特征：POST请求体为Base64字符串，解密后是序列化的命令数据',
        '- 检测：请求体熵值（entropy）异常高——正常表单数据的熵值低，加密数据的熵值接近随机',
        '',
        '**特征3：User-Agent异常**',
        '- 蚁剑默认UA：`antSword/v2.1`',
        '- 冰蝎默认UA：可自定义但默认有规律',
        '- 检测：建立正常UA白名单，排除非白名单UA的请求',
        '',
        '**检测命令**（流量层面）**：**',
        '```bash',
        '# 检测同一文件的高频POST请求（心跳包特征）',
        "grep \"POST\" access.log | awk '{print $7}' | sort | uniq -c | sort -rn | head -10",
        '',
        '# 检测请求体熵值（需要Python脚本）',
        "python3 -c \"import sys,math; [print(f'{l}: entropy={sum(-p*math.log2(p) for p in [l.count(c)/len(l) for c in set(l)])}') for l in sys.stdin]\" < post_bodies.txt",
        '```',
    ]),
])

# Day 28 (面试) — currently 249, need ~260 more  
D28_DEEP = deep_dive_block('初级蓝队面试模拟——高频题完整版', [
    ('技术面高频问答（15题精选）', [
        '以下是初级蓝队面试最高频的15道技术题，建议逐题准备：',
        '',
        '**基础知识类（5题）**：',
        '1. OSI七层模型每层对应哪些协议和攻击？→ 面试官想看的是\"理论联系实际\"的能力',
        '2. TCP三次握手的过程，每个包的标志位是什么？→ 基础中的基础，答不上来直接淘汰',
        '3. HTTP常见状态码200/301/302/400/403/404/500的含义和安全意义？→ 重点讲安全意义',
        '4. Linux三剑客（grep/awk/sed）的定位和常用场景？→ 要给具体的使用案例',
        '5. Windows事件ID 4624/4625/4672/4688的含义？→ 必须准确无误',
        '',
        '**工具与技能类（5题）**：',
        '6. Wireshark中如何过滤特定IP和端口的流量？→ 展示过滤语法和实际分析思路',
        '7. 给你一份10000行的Web日志，你如何分析是否有攻击？→ 展示分析流程和方法论',
        '8. Nmap的-sS和-sT扫描有什么区别？怎么检测？→ 展示对攻击工具的理解',
        '9. VirusTotal怎么用？有哪些限制？→ 展示威胁情报分析能力',
        '10. 如何从系统日志中排查入侵痕迹？→ 展示应急排查的系统性思路',
        '',
        '**实战场景类（5题）**：',
        '11. 描述一次你处理过的安全事件，从发现到闭环的全过程→ PDCERF模型套上去',
        '12. WAF报告了一条SQL注入告警，你怎么研判？→ 核查→取证→研判→定级→处置',
        '13. 你发现某台服务器的CPU突然100%，怎么排查？→ 进程排查→网络连接→日志分析',
        '14. 护网期间你值夜班，收到20条告警，怎么处理？→ 分级→批量研判→优先处置',
        '15. 你觉得自己的技术短板在哪里？怎么弥补？→ 诚实 + 学习计划',
    ]),
    ('面试中的\"加分项\"和\"减分项\"', [
        '**加分项**：',
        '- 用\"故事\"回答问题（真实的事件+你的分析过程+处置结果+经验总结）',
        '- 展示你的知识管理体系（\"我有自己的笔记库/命令速查手册/检测规则库\"）',
        '- 提出\"纵深防御\"的思维方式（不是单一手段，而是多层防护）',
        '- 主动提问（\"公司目前主要面临哪些安全威胁？安全团队规模多大？安全设备有哪些？\"）',
        '- 展示持续学习能力（关注的公众号/博客/社区+最近读的安全文章/报告）',
        '',
        '**减分项**：',
        '- 只会说\"装个WAF就行了\"——暴露思维单一',
        '- 攻击工具聊得很熟但防御手段说不清楚——暴露出攻强守弱（蓝队面试大忌）',
        '- \"大概是...\"\"好像是...\"——含糊其辞，暴露知识不扎实',
        '- \"这个我不太清楚但我知道XXX\"——如果确实不懂，直接承认并表示愿意学，不要硬扯',
        '- 过度自信或过度自贬——保持专业谦逊的态度',
        '- 工资是你问的第一个问题——先展示你能创造什么价值',
    ]),
    ('面试后的复盘与改进', [
        '**每次面试都是学习机会，无论结果如何**：',
        '',
        '1. **面试后立即记录**：记下被问到的问题，特别是你没答好或不会答的',
        '2. **针对性补课**：对于没答好的问题，回去后当天就查资料学习',
        '3. **更新面试题库**：维护一份个人面试题库，每次面试后追加新题和优化答案',
        '4. **模拟练习**：找同事/朋友做模拟面试，特别是软技能型问题（\"你的优缺点？职业规划？\"）',
        '5. **迭代简历**：根据面试反馈调整简历——哪些经验被追问了（说明有吸引力），哪些被跳过了（说明不重要）',
        '',
        '**核心心态**：初级岗位面试的核心不是\"你什么都会\"，而是\"你有扎实的基础 + 正确的学习能力 + 对安全工作的热情\"。面试官更看重潜力而非现成的知识储备。',
    ]),
])

# ======= APPEND ALL =======
all_deep = {
    3: D3_DEEP,
    4: D4_DEEP,
    5: D5_DEEP,
    8: D8_DEEP,
    9: D9_DEEP,
    10: D10_DEEP,
    15: D15_DEEP,
    18: D18_DEEP,
    20: D20_DEEP,
    22: D22_DEEP,
    26: D26_DEEP,
    28: D28_DEEP,
}

for day, content in all_deep.items():
    append_to(day, content)

print('')
print('Round 3 supplements applied!')
